# Copyright (C) 2025 EthyrosAI LLC / Jason Kempf
#
# This file is part of ModelCypher.
#
# ModelCypher is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ModelCypher is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with ModelCypher.  If not, see <https://www.gnu.org/licenses/>.

"""Null space computation and result types.

Provides numerical rank computation, null space basis extraction, and
variance-based null space analysis for activation matrices.
"""

from __future__ import annotations

import logging
import math
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from modelcypher.core.domain.geometry.numerical_stability import (
    _promote_precision_float32 as _promote_precision,
)
from modelcypher.core.domain.geometry.numerical_stability import (
    machine_epsilon,
    sqrt_scalar,
)

if TYPE_CHECKING:
    from modelcypher.ports.backend import Array, Backend
    from modelcypher.ports.model_architecture import ModelArchitecturePort

logger = logging.getLogger(__name__)


def _get_model_architecture(model: Any) -> "ModelArchitecturePort":
    """Get architecture wrapper for model, inferring config if needed.

    Tries to get config from model attributes, then uses architecture protocol.
    """
    from modelcypher.ports.model_architecture_factory import get_model_architecture

    # Try to get config from model
    config: dict = {}
    if hasattr(model, "config"):
        model_config = model.config
        if hasattr(model_config, "to_dict"):
            config = model_config.to_dict()
        elif isinstance(model_config, dict):
            config = model_config
    elif hasattr(model, "model") and hasattr(model.model, "config"):
        model_config = model.model.config
        if hasattr(model_config, "to_dict"):
            config = model_config.to_dict()
        elif isinstance(model_config, dict):
            config = model_config

    # If config is empty, try to infer model_type from class name
    if not config.get("model_type"):
        model_class = type(model).__module__ + "." + type(model).__name__
        model_class_lower = model_class.lower()
        if "lfm2" in model_class_lower or "lfm" in model_class_lower:
            config["model_type"] = "lfm2"
        elif "llama" in model_class_lower:
            config["model_type"] = "llama"
        elif "qwen" in model_class_lower:
            config["model_type"] = "qwen2"
        elif "gpt2" in model_class_lower:
            config["model_type"] = "gpt2"
        elif "bert" in model_class_lower:
            config["model_type"] = "bert"

    return get_model_architecture(model, config=config)


@dataclass
class OrthogonalProbeResult:
    """Result of generating a single orthogonal probe."""

    token_ids: list[int]
    text: str
    orthogonal_component_norm: float


@dataclass
class SequenceProbeResult:
    """Result of generating a null-space activating sequence.

    Sequences are generated by vocabulary scoring:
    1. Score vocabulary tokens for null-space activation
    2. Select numerically significant tokens up to the null-space rank
    """

    token_ids: list[int]
    text: str
    null_space_norm: float  # ||U_null^T @ activation|| - how much null space activated
    seed_token_id: int  # Original vocab token used as seed
    gradient_steps: int  # 0 for closed-form selection
    improvement_ratio: float  # 1.0 when no optimization is applied


@dataclass
class RankAugmentationResult:
    """Result of iterative rank augmentation."""

    initial_rank: int
    final_rank: int
    hidden_dim: int
    probes_generated: int
    iterations: int
    full_rank_achieved: bool
    generated_probes: list[OrthogonalProbeResult]


def compute_numerical_rank(
    activations: "Array",
    backend: "Backend",
    debug_layer: int | None = None,
) -> tuple[int, int]:
    """Compute numerical rank via Gram eigenvalues.

    Uses G = A @ A.T when n < d (typical case): O(n^3) instead of O(nd^2).
    Eigenvalues of Gram matrix lambda = sigma^2 (squared singular values).
    Threshold: sigma > sigma_max * sqrt(eps) -> lambda > lambda_max * eps

    Args:
        activations: Activation matrix [n_samples, hidden_dim].
        backend: Backend for tensor operations.
        debug_layer: If set, log detailed spectrum info for this layer.

    Returns:
        Tuple (rank, hidden_dim).
    """
    b = backend
    acts = _promote_precision(activations, b)
    b.eval(acts)

    shape = b.shape(acts)
    n_samples = int(shape[0])
    hidden_dim = int(shape[1])

    if n_samples == 0 or hidden_dim == 0:
        return 0, hidden_dim

    # Machine epsilon for threshold
    eps = float(machine_epsilon(b, acts))

    # Gram method: eigenvalues lambda = sigma^2 (squared singular values)
    # Choose smaller Gram matrix based on n vs d:
    # - If n < d: G = A @ A.T is n x n, O(n^3)
    # - If n >= d: G = A.T @ A is d x d, O(d^3)
    # Rank is at most min(n, d) regardless of which we use.
    if n_samples < hidden_dim:
        # G = A @ A.T: n x n (smaller when n < d)
        G = b.matmul(acts, b.transpose(acts))
    else:
        # G = A.T @ A: d x d (smaller when n >= d)
        G = b.matmul(b.transpose(acts), acts)
    b.eval(G)

    # Eigenvalues of symmetric PSD matrix (sorted ascending by eigvalsh)
    eigvals = b.eigvalsh(G)
    b.eval(eigvals)

    # Get max eigenvalue (last element since eigvalsh sorts ascending)
    max_eig_arr = eigvals[-1]
    b.eval(max_eig_arr)
    max_eig = float(b.to_scalar(max_eig_arr))

    # Threshold in eigenvalue space: lambda > lambda_max * eps
    # (equivalent to sigma > sigma_max * sqrt(eps) since lambda = sigma^2)
    threshold_sq = max_eig * eps

    # Count eigenvalues above threshold
    rank_mask = eigvals > threshold_sq
    rank_arr = b.sum(b.astype(rank_mask, "int32"))
    b.eval(rank_arr)
    rank = int(b.to_scalar(rank_arr))

    # DEBUG: Log spectrum for specific layers
    if debug_layer is not None:
        n_eigs = int(b.shape(eigvals)[0])
        top_10_indices = min(10, n_eigs)

        # Top 10 (largest eigenvalues - at the end since ascending)
        if n_eigs >= 10:
            start_idx = n_eigs - 10
            eig_top = b.take(eigvals, b.arange(start_idx, n_eigs, dtype="int32"), axis=0)
        else:
            eig_top = eigvals
        b.eval(eig_top)
        top_10_vals = b.tolist(eig_top)[::-1]  # Reverse to get descending

        # Bottom 10 (smallest eigenvalues - at the start)
        eig_bottom = b.take(eigvals, b.arange(top_10_indices, dtype="int32"), axis=0)
        b.eval(eig_bottom)
        bottom_10_vals = b.tolist(eig_bottom)

        logger.info(
            "GRAM RANK Layer %d: n=%d, d=%d, rank=%d, lambda_max=%.6e, threshold=%.6e, "
            "top_10_lambda=%s, bottom_10_lambda=%s",
            debug_layer, n_samples, hidden_dim, rank, max_eig, threshold_sq,
            [f"{v:.4e}" for v in top_10_vals],
            [f"{v:.4e}" for v in bottom_10_vals],
        )

    return rank, hidden_dim


def compute_null_space_basis(
    activations: "Array",
    rank: int,
    backend: "Backend",
) -> "Array | None":
    """Compute basis for orthogonal complement of probe subspace.

    Uses eigendecomposition of A^T @ A to find directions with smallest
    eigenvalues (the null space of the current probe coverage).

    Args:
        activations: Activation matrix [n_samples, hidden_dim].
        rank: Current numerical rank of activations.
        backend: Backend for tensor operations.

    Returns:
        Null space basis [hidden_dim, null_rank], or None if already full rank.
    """
    b = backend
    logger.info("NULL SPACE: Computing basis for rank=%d activations...", rank)

    try:
        acts = _promote_precision(activations, b)
        b.eval(acts)

        hidden_dim = int(b.shape(acts)[1])
        null_rank = hidden_dim - rank
        logger.info("NULL SPACE: hidden_dim=%d, null_rank=%d", hidden_dim, null_rank)

        if null_rank <= 0:
            logger.info("NULL SPACE: Already full rank, returning None")
            return None  # Already full rank

        # Covariance in hidden_dim space: A^T @ A
        logger.info("NULL SPACE: Computing covariance matrix...")
        cov = b.matmul(b.transpose(acts), acts)
        b.eval(cov)

        # Eigendecomposition (eigh returns ascending eigenvalues)
        logger.info("NULL SPACE: Computing eigendecomposition...")
        eigvals, eigvecs = b.eigh(cov)
        b.eval(eigvals, eigvecs)

        # First null_rank eigenvectors (smallest eigenvalues) form the null space
        U_null = eigvecs[:, :null_rank]
        b.eval(U_null)

        logger.info("NULL SPACE: Computed basis with shape %s", b.shape(U_null))
        return U_null

    except Exception as e:
        logger.error("NULL SPACE: Computation FAILED: %s: %s", type(e).__name__, e)
        import traceback
        logger.error("TRACEBACK:\n%s", traceback.format_exc())
        raise


@dataclass
class VarianceNullSpaceResult:
    """Result of variance-based null space computation.

    Derived from activation covariance.
    """

    utilized_basis: "Array"  # Eigenvectors of high-variance directions [hidden_dim, utilized_rank]
    available_basis: "Array"  # Eigenvectors of low-variance directions [hidden_dim, available_rank]
    utilized_rank: int  # Number of high-variance (semantically important) directions
    available_rank: int  # Number of low-variance (available for transfer) directions
    eigenvalues: "Array"  # All eigenvalues in descending order
    variance_threshold: float  # Threshold used to split utilized/available


def compute_variance_null_space(
    activations: "Array",
    backend: "Backend",
    variance_threshold: float | None = None,
) -> VarianceNullSpaceResult:
    """Compute null space based on activation variance, not trajectory coverage.

    Splits directions by variance threshold into utilized and available bases.

    Args:
        activations: Activation matrix [n_probes, hidden_dim].
        backend: Backend for tensor operations.
        variance_threshold: Optional threshold for splitting utilized/available.
            If None, uses sqrt(machine_epsilon) * max_eigenvalue.

    Returns:
        VarianceNullSpaceResult with utilized and available subspace bases.
    """
    b = backend
    acts = _promote_precision(activations, b)
    b.eval(acts)

    n_probes = int(b.shape(acts)[0])
    hidden_dim = int(b.shape(acts)[1])

    logger.info(
        "VARIANCE NULL SPACE: Computing from [%d, %d] activations",
        n_probes, hidden_dim
    )

    # Center activations (mean subtraction)
    A_centered = acts - b.mean(acts, axis=0, keepdims=True)
    b.eval(A_centered)

    # Compute activation covariance: C = A.T @ A / n_probes
    # This gives eigenvalues proportional to variance in each direction
    C = b.matmul(b.transpose(A_centered), A_centered)
    C = C / float(n_probes)
    b.eval(C)

    # Eigendecomposition (eigh returns ascending eigenvalues)
    eigenvalues, V = b.eigh(C)
    b.eval(eigenvalues, V)

    # Reverse to descending order (highest variance first)
    reverse_idx = b.arange(hidden_dim - 1, -1, -1)
    eigenvalues = b.take(eigenvalues, reverse_idx, axis=0)
    V = b.take(V, reverse_idx, axis=1)
    b.eval(eigenvalues, V)

    # Clamp negative eigenvalues to zero (numerical noise)
    eigenvalues = b.maximum(eigenvalues, b.zeros_like(eigenvalues))
    b.eval(eigenvalues)

    # Determine threshold based on cumulative variance
    if variance_threshold is None:
        # Use cumulative variance threshold: keep dimensions until we capture
        # a target fraction of total variance. This is more robust than
        # sqrt(eps) * max_eigenvalue for concentrated spectra.
        #
        # Target: 99.9% variance captured (sqrt(eps) ~ 3e-4 for float32)
        eps = machine_epsilon(b, eigenvalues)
        target_fraction = 1.0 - sqrt_scalar(eps, b)

        # Compute cumulative variance
        total_variance_arr = b.sum(eigenvalues)
        b.eval(total_variance_arr)
        total_variance = float(b.to_scalar(total_variance_arr))

        if total_variance > 0:
            cumsum = b.cumsum(eigenvalues, axis=0)
            b.eval(cumsum)
            cumulative_fraction = cumsum / total_variance

            # Find first index where cumulative fraction exceeds target
            exceeds_target = cumulative_fraction >= target_fraction
            b.eval(exceeds_target)

            # Sum of True values up to first True gives the utilized count
            # Use argmax on exceeds_target to find first True (or last if none)
            first_exceeds_arr = b.argmax(b.astype(exceeds_target, "int32"))
            b.eval(first_exceeds_arr)
            first_exceeds = int(b.to_scalar(first_exceeds_arr))

            # The utilized_rank is first_exceeds + 1 (since we want to include that dimension)
            # But if no dimension exceeds target, use all dimensions
            if not bool(b.to_scalar(exceeds_target[first_exceeds])):
                # No dimension exceeds target, use all
                variance_threshold = 0.0
            else:
                # Use the eigenvalue at this index, then subtract a Weyl bound
                # perturbation margin to avoid misclassification near the cutoff.
                # |Δλ| <= sqrt(n) * eps(dtype) * λ_max for symmetric eigensolvers.
                threshold_eig = eigenvalues[first_exceeds]
                b.eval(threshold_eig)
                lambda_max_arr = eigenvalues[0]
                b.eval(lambda_max_arr)
                lambda_max = float(b.to_scalar(lambda_max_arr))
                dtype_eps = float(b.finfo(eigenvalues.dtype).eps)
                eig_perturbation = math.sqrt(hidden_dim) * dtype_eps * lambda_max
                variance_threshold = max(
                    0.0,
                    float(b.to_scalar(threshold_eig)) - eig_perturbation,
                )
        else:
            variance_threshold = 0.0

    # Split into utilized (high variance) and available (low variance)
    utilized_mask = eigenvalues > variance_threshold
    utilized_count_arr = b.sum(b.astype(utilized_mask, "int32"))
    b.eval(utilized_count_arr)
    utilized_rank = int(b.to_scalar(utilized_count_arr))
    available_rank = hidden_dim - utilized_rank

    # Utilized subspace: first utilized_rank eigenvectors (highest variance)
    U_utilized = V[:, :utilized_rank] if utilized_rank > 0 else b.zeros((hidden_dim, 0))
    b.eval(U_utilized)

    # Available subspace: remaining eigenvectors (lowest variance)
    U_available = V[:, utilized_rank:] if available_rank > 0 else b.zeros((hidden_dim, 0))
    b.eval(U_available)

    # Log utilization statistics
    total_variance_arr = b.sum(eigenvalues)
    utilized_variance_arr = b.sum(eigenvalues[:utilized_rank]) if utilized_rank > 0 else b.array(0.0)
    b.eval(total_variance_arr, utilized_variance_arr)

    total_variance = float(b.to_scalar(total_variance_arr))
    utilized_variance = float(b.to_scalar(utilized_variance_arr))

    if total_variance > 0:
        variance_captured = utilized_variance / total_variance
    else:
        variance_captured = 0.0

    logger.info(
        "VARIANCE NULL SPACE: utilized_rank=%d (%.1f%%), available_rank=%d (%.1f%%), "
        "variance_captured=%.4f, threshold=%.4e",
        utilized_rank, 100.0 * utilized_rank / hidden_dim,
        available_rank, 100.0 * available_rank / hidden_dim,
        variance_captured, variance_threshold
    )

    return VarianceNullSpaceResult(
        utilized_basis=U_utilized,
        available_basis=U_available,
        utilized_rank=utilized_rank,
        available_rank=available_rank,
        eigenvalues=eigenvalues,
        variance_threshold=variance_threshold,
    )


__all__ = [
    # Helper
    "_get_model_architecture",
    # Result types
    "OrthogonalProbeResult",
    "SequenceProbeResult",
    "RankAugmentationResult",
    "VarianceNullSpaceResult",
    # Functions
    "compute_numerical_rank",
    "compute_null_space_basis",
    "compute_variance_null_space",
]
