# Copyright (C) 2025 EthyrosAI LLC / Jason Kempf
#
# This file is part of ModelCypher.
#
# ModelCypher is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ModelCypher is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with ModelCypher.  If not, see <https://www.gnu.org/licenses/>.

"""Orthogonal probe generation for full-rank alignment.

Generates probes via closed-form null-space scoring to maximize activation in
directions orthogonal to the current probe subspace. This enables systematic
rank augmentation until activations span the full hidden dimension.

The algorithm:
1. Compute current activation rank via SVD
2. Find null space basis (eigenvectors of A^T @ A with small eigenvalues)
3. Score vocabulary tokens by ||U_null^T @ activation||
4. Select numerically significant tokens up to null-space rank
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from modelcypher.core.domain.geometry.numerical_stability import (
    machine_epsilon,
    regularization_epsilon,
    sqrt_scalar,
)
from modelcypher.core.domain.geometry.precision_utils import (
    _promote_precision_float32 as _promote_precision,
)

if TYPE_CHECKING:
    from modelcypher.ports.backend import Array, Backend

logger = logging.getLogger(__name__)


@dataclass
class OrthogonalProbeResult:
    """Result of generating a single orthogonal probe."""

    token_ids: list[int]
    text: str
    orthogonal_component_norm: float


@dataclass
class SequenceProbeResult:
    """Result of generating a null-space activating sequence.

    Sequences are generated by closed-form vocabulary scoring:
    1. Score vocabulary tokens for null-space activation
    2. Select numerically significant tokens up to the null-space rank
    """

    token_ids: list[int]
    text: str
    null_space_norm: float  # ||U_null^T @ activation|| - how much null space activated
    seed_token_id: int  # Original vocab token used as seed
    gradient_steps: int  # 0 for closed-form selection
    improvement_ratio: float  # 1.0 when no optimization is applied


@dataclass
class RankAugmentationResult:
    """Result of iterative rank augmentation."""

    initial_rank: int
    final_rank: int
    hidden_dim: int
    probes_generated: int
    iterations: int
    full_rank_achieved: bool
    generated_probes: list[OrthogonalProbeResult]


def compute_numerical_rank(
    activations: "Array",
    backend: "Backend",
    debug_layer: int | None = None,
) -> tuple[int, int]:
    """Compute numerical rank via Gram eigenvalues (exact, faster).

    Uses G = A @ A.T when n < d (typical case): O(n³) instead of O(nd²).
    Eigenvalues of Gram matrix λ = σ² (squared singular values).
    Threshold: σ > σ_max * sqrt(eps) → λ > λ_max * eps

    Args:
        activations: Activation matrix [n_samples, hidden_dim].
        backend: Backend for tensor operations.
        debug_layer: If set, log detailed spectrum info for this layer.

    Returns:
        Tuple (rank, hidden_dim).
    """
    b = backend
    acts = _promote_precision(activations, b)
    b.eval(acts)

    shape = b.shape(acts)
    n_samples = int(shape[0])
    hidden_dim = int(shape[1])

    if n_samples == 0 or hidden_dim == 0:
        return 0, hidden_dim

    # Machine epsilon for threshold
    eps = float(machine_epsilon(b, acts))

    # Gram method: G = A @ A.T gives eigenvalues λ = σ²
    # This is O(n³) vs SVD's O(nd²) when n < d
    G = b.matmul(acts, b.transpose(acts))
    b.eval(G)

    # Eigenvalues of symmetric PSD matrix (sorted ascending by eigvalsh)
    eigvals = b.eigvalsh(G)
    b.eval(eigvals)

    # Get max eigenvalue (last element since eigvalsh sorts ascending)
    max_eig_arr = eigvals[-1]
    b.eval(max_eig_arr)
    max_eig = float(b.to_scalar(max_eig_arr))

    # Threshold in eigenvalue space: λ > λ_max * eps
    # (equivalent to σ > σ_max * sqrt(eps) since λ = σ²)
    threshold_sq = max_eig * eps

    # Count eigenvalues above threshold
    rank_mask = eigvals > threshold_sq
    rank_arr = b.sum(b.astype(rank_mask, "int32"))
    b.eval(rank_arr)
    rank = int(b.to_scalar(rank_arr))

    # DEBUG: Log spectrum for specific layers
    if debug_layer is not None:
        n_eigs = int(b.shape(eigvals)[0])
        top_10_indices = min(10, n_eigs)

        # Top 10 (largest eigenvalues - at the end since ascending)
        if n_eigs >= 10:
            start_idx = n_eigs - 10
            eig_top = b.take(eigvals, b.arange(start_idx, n_eigs, dtype="int32"), axis=0)
        else:
            eig_top = eigvals
        b.eval(eig_top)
        top_10_vals = b.tolist(eig_top)[::-1]  # Reverse to get descending

        # Bottom 10 (smallest eigenvalues - at the start)
        eig_bottom = b.take(eigvals, b.arange(top_10_indices, dtype="int32"), axis=0)
        b.eval(eig_bottom)
        bottom_10_vals = b.tolist(eig_bottom)

        logger.info(
            "GRAM RANK Layer %d: n=%d, d=%d, rank=%d, λ_max=%.6e, threshold=%.6e, "
            "top_10_λ=%s, bottom_10_λ=%s",
            debug_layer, n_samples, hidden_dim, rank, max_eig, threshold_sq,
            [f"{v:.4e}" for v in top_10_vals],
            [f"{v:.4e}" for v in bottom_10_vals],
        )

    return rank, hidden_dim


def compute_null_space_basis(
    activations: "Array",
    rank: int,
    backend: "Backend",
) -> "Array | None":
    """Compute basis for orthogonal complement of probe subspace.

    Uses eigendecomposition of A^T @ A to find directions with smallest
    eigenvalues (the null space of the current probe coverage).

    Args:
        activations: Activation matrix [n_samples, hidden_dim].
        rank: Current numerical rank of activations.
        backend: Backend for tensor operations.

    Returns:
        Null space basis [hidden_dim, null_rank], or None if already full rank.
    """
    b = backend
    logger.info("NULL SPACE: Computing basis for rank=%d activations...", rank)

    try:
        acts = _promote_precision(activations, b)
        b.eval(acts)

        hidden_dim = int(b.shape(acts)[1])
        null_rank = hidden_dim - rank
        logger.info("NULL SPACE: hidden_dim=%d, null_rank=%d", hidden_dim, null_rank)

        if null_rank <= 0:
            logger.info("NULL SPACE: Already full rank, returning None")
            return None  # Already full rank

        # Covariance in hidden_dim space: A^T @ A
        logger.info("NULL SPACE: Computing covariance matrix...")
        cov = b.matmul(b.transpose(acts), acts)
        b.eval(cov)

        # Eigendecomposition (eigh returns ascending eigenvalues)
        logger.info("NULL SPACE: Computing eigendecomposition...")
        eigvals, eigvecs = b.eigh(cov)
        b.eval(eigvals, eigvecs)

        # First null_rank eigenvectors (smallest eigenvalues) form the null space
        U_null = eigvecs[:, :null_rank]
        b.eval(U_null)

        logger.info("NULL SPACE: Computed basis with shape %s", b.shape(U_null))
        return U_null

    except Exception as e:
        logger.error("NULL SPACE: Computation FAILED: %s: %s", type(e).__name__, e)
        import traceback
        logger.error("TRACEBACK:\n%s", traceback.format_exc())
        raise


@dataclass
class VarianceNullSpaceResult:
    """Result of variance-based null space computation.

    Based on LoRA-Null (AAAI 2026): "The null space of activations is more accurate."

    High-variance directions = utilized (preserve target's behavior)
    Low-variance directions = available (add source knowledge)
    """

    utilized_basis: "Array"  # Eigenvectors of high-variance directions [hidden_dim, utilized_rank]
    available_basis: "Array"  # Eigenvectors of low-variance directions [hidden_dim, available_rank]
    utilized_rank: int  # Number of high-variance (semantically important) directions
    available_rank: int  # Number of low-variance (available for transfer) directions
    eigenvalues: "Array"  # All eigenvalues in descending order
    variance_threshold: float  # Threshold used to split utilized/available


def compute_variance_null_space(
    activations: "Array",
    backend: "Backend",
    variance_threshold: float | None = None,
) -> VarianceNullSpaceResult:
    """Compute null space based on activation variance, not trajectory coverage.

    This replaces trajectory-based null space computation when trajectory spans
    full space. The key insight from LoRA-Null (AAAI 2026): "The effective ranks
    of input activations are much smaller than those of pre-trained weights.
    The null space of activations is more accurate."

    High-variance directions = utilized (preserve target's behavior)
    Low-variance directions = available (add source knowledge)

    Apple's research (ICML 2024) shows models use only ~20-35% of available space.

    Args:
        activations: Activation matrix [n_probes, hidden_dim].
        backend: Backend for tensor operations.
        variance_threshold: Optional threshold for splitting utilized/available.
            If None, uses sqrt(machine_epsilon) * max_eigenvalue.

    Returns:
        VarianceNullSpaceResult with utilized and available subspace bases.
    """
    b = backend
    acts = _promote_precision(activations, b)
    b.eval(acts)

    n_probes = int(b.shape(acts)[0])
    hidden_dim = int(b.shape(acts)[1])

    logger.info(
        "VARIANCE NULL SPACE: Computing from [%d, %d] activations",
        n_probes, hidden_dim
    )

    # Center activations (mean subtraction)
    A_centered = acts - b.mean(acts, axis=0, keepdims=True)
    b.eval(A_centered)

    # Compute activation covariance: C = A.T @ A / n_probes
    # This gives eigenvalues proportional to variance in each direction
    C = b.matmul(b.transpose(A_centered), A_centered)
    C = C / float(n_probes)
    b.eval(C)

    # Eigendecomposition (eigh returns ascending eigenvalues)
    eigenvalues, V = b.eigh(C)
    b.eval(eigenvalues, V)

    # Reverse to descending order (highest variance first)
    reverse_idx = b.arange(hidden_dim - 1, -1, -1)
    eigenvalues = b.take(eigenvalues, reverse_idx, axis=0)
    V = b.take(V, reverse_idx, axis=1)
    b.eval(eigenvalues, V)

    # Clamp negative eigenvalues to zero (numerical noise)
    eigenvalues = b.maximum(eigenvalues, b.zeros_like(eigenvalues))
    b.eval(eigenvalues)

    # Determine threshold
    if variance_threshold is None:
        # Use sqrt(eps) * max_eigenvalue as threshold
        # This is numerically derived, not a heuristic
        eps = machine_epsilon(b, eigenvalues)
        max_eig_arr = b.max(eigenvalues)
        b.eval(max_eig_arr)
        max_eig = float(b.to_scalar(max_eig_arr))
        variance_threshold = sqrt_scalar(eps, b) * max_eig

    # Split into utilized (high variance) and available (low variance)
    utilized_mask = eigenvalues > variance_threshold
    utilized_count_arr = b.sum(b.astype(utilized_mask, "int32"))
    b.eval(utilized_count_arr)
    utilized_rank = int(b.to_scalar(utilized_count_arr))
    available_rank = hidden_dim - utilized_rank

    # Utilized subspace: first utilized_rank eigenvectors (highest variance)
    U_utilized = V[:, :utilized_rank] if utilized_rank > 0 else b.zeros((hidden_dim, 0))
    b.eval(U_utilized)

    # Available subspace: remaining eigenvectors (lowest variance)
    U_available = V[:, utilized_rank:] if available_rank > 0 else b.zeros((hidden_dim, 0))
    b.eval(U_available)

    # Log utilization statistics
    total_variance_arr = b.sum(eigenvalues)
    utilized_variance_arr = b.sum(eigenvalues[:utilized_rank]) if utilized_rank > 0 else b.array(0.0)
    b.eval(total_variance_arr, utilized_variance_arr)

    total_variance = float(b.to_scalar(total_variance_arr))
    utilized_variance = float(b.to_scalar(utilized_variance_arr))

    if total_variance > 0:
        variance_captured = utilized_variance / total_variance
    else:
        variance_captured = 0.0

    logger.info(
        "VARIANCE NULL SPACE: utilized_rank=%d (%.1f%%), available_rank=%d (%.1f%%), "
        "variance_captured=%.4f, threshold=%.4e",
        utilized_rank, 100.0 * utilized_rank / hidden_dim,
        available_rank, 100.0 * available_rank / hidden_dim,
        variance_captured, variance_threshold
    )

    return VarianceNullSpaceResult(
        utilized_basis=U_utilized,
        available_basis=U_available,
        utilized_rank=utilized_rank,
        available_rank=available_rank,
        eigenvalues=eigenvalues,
        variance_threshold=variance_threshold,
    )


class OrthogonalProbeGenerator:
    """Generates probes that activate in orthogonal directions.

    Uses closed-form null-space scoring to avoid heuristic optimization knobs.
    """

    def __init__(self, backend: "Backend") -> None:
        """Initialize generator.

        Args:
            backend: Backend for tensor operations.
        """
        self.backend = backend

    def generate_orthogonal_probe(
        self,
        model: Any,
        tokenizer: Any,
        U_null: "Array",
        layer_idx: int,
    ) -> OrthogonalProbeResult | None:
        """Generate a probe that activates in the null space.

        Args:
            model: The model to generate probes for.
            tokenizer: Tokenizer for decoding.
            U_null: Null space basis [hidden_dim, null_rank].
            layer_idx: Target layer index for activation.

        Returns:
            OrthogonalProbeResult or None if generation fails.
        """
        top_tokens = find_null_space_tokens_closed_form(
            model=model,
            U_null=U_null,
            layer_idx=layer_idx,
            backend=self.backend,
        )

        if not top_tokens:
            logger.warning("ORTHOGONAL PROBE: No tokens found for null space")
            return None

        token_id, score = top_tokens[0]
        try:
            text = tokenizer.decode([token_id], skip_special_tokens=True)
        except Exception:
            text = "<decode-failed>"

        return OrthogonalProbeResult(
            token_ids=[token_id],
            text=text,
            orthogonal_component_norm=score,
        )

    def augment_rank_iteratively(
        self,
        model: Any,
        tokenizer: Any,
        activations: "Array",
        layer_idx: int,
    ) -> RankAugmentationResult:
        """Augment rank using closed-form token selection."""
        return augment_rank_closed_form(
            model=model,
            tokenizer=tokenizer,
            activations=activations,
            layer_idx=layer_idx,
            backend=self.backend,
        )


def validate_full_rank_coverage(
    source_activations: dict[int, "Array"],
    target_activations: dict[int, "Array"],
    backend: "Backend",
) -> dict[int, dict]:
    """Validate rank coverage per layer.

    Full rank is achieved when both source and target have matching numerical rank.
    The "effective dimensionality" is bounded by the target's numerical rank, which
    reflects the layer's intrinsic geometry. Middle layers may have lower effective
    dimensionality due to representation compression.

    Args:
        source_activations: Source activations by layer.
        target_activations: Target activations by layer.
        backend: Backend for tensor operations.

    Returns:
        Dict mapping layer -> {rank, dim, deficit, full_rank_achieved}.
    """
    b = backend
    results: dict[int, dict] = {}

    # Get common layers
    common_layers = set(source_activations.keys()) & set(target_activations.keys())

    for layer_idx in sorted(common_layers):
        src_acts = source_activations[layer_idx]
        tgt_acts = target_activations[layer_idx]

        # Stack if list
        if isinstance(src_acts, list):
            src_acts = b.stack(src_acts, axis=0)
        if isinstance(tgt_acts, list):
            tgt_acts = b.stack(tgt_acts, axis=0)

        b.eval(src_acts, tgt_acts)

        # Compute ranks
        src_rank, src_dim = compute_numerical_rank(src_acts, b)
        tgt_rank, tgt_dim = compute_numerical_rank(tgt_acts, b)

        # =====================================================================
        # FULL RANK REQUIREMENT: BOTH models must have full rank
        # =====================================================================
        # For F = pinv(A_src) @ A_tgt:
        # - If A_src has rank < src_dim, then F is undefined for (src_dim - src_rank) directions
        # - If A_tgt has rank < tgt_dim, then we can't span all of target's space
        #
        # Cross-dimensional alignment (e.g., 4096 → 2048) still requires:
        # - Source: full rank (src_rank == src_dim) so F covers all source directions
        # - Target: full rank (tgt_rank == tgt_dim) so we span the full target space
        #
        # "Dark" dimensions in source (where probes don't activate) get arbitrary
        # coefficients in F, which causes garbage in the transplanted weights.
        # =====================================================================
        src_full_rank = src_rank >= src_dim
        tgt_full_rank = tgt_rank >= tgt_dim
        full_rank = src_full_rank and tgt_full_rank

        # Deficits for each model
        src_deficit = src_dim - src_rank
        tgt_deficit = tgt_dim - tgt_rank
        total_deficit = src_deficit + tgt_deficit

        # For backward compatibility, keep alignment_rank as min
        alignment_rank = min(src_rank, tgt_rank)

        results[layer_idx] = {
            "source_rank": src_rank,
            "source_dim": src_dim,
            "source_deficit": src_deficit,
            "source_full_rank": src_full_rank,
            "target_rank": tgt_rank,
            "target_dim": tgt_dim,
            "target_deficit": tgt_deficit,
            "target_full_rank": tgt_full_rank,
            "alignment_rank": alignment_rank,
            "deficit": total_deficit,
            "full_rank_achieved": full_rank,
            "coverage_ratio": (src_rank / src_dim * tgt_rank / tgt_dim) if src_dim > 0 and tgt_dim > 0 else 1.0,
        }

        if not full_rank:
            logger.info(
                "RANK COVERAGE Layer %d: src=%d/%d (%s), tgt=%d/%d (%s), total_deficit=%d",
                layer_idx,
                src_rank, src_dim, "FULL" if src_full_rank else "DEFICIT",
                tgt_rank, tgt_dim, "FULL" if tgt_full_rank else "DEFICIT",
                total_deficit,
            )
        else:
            logger.debug(
                "RANK COVERAGE Layer %d: FULL RANK (src=%d/%d, tgt=%d/%d)",
                layer_idx,
                src_rank, src_dim,
                tgt_rank, tgt_dim,
            )

    return results


def score_tokens_for_null_space(
    activations_by_token: "Array",
    U_null: "Array",
    backend: "Backend",
) -> "Array":
    """Score tokens by how much they activate null space directions.

    This is the closed-form approach: no iteration, just matrix multiply.

    Args:
        activations_by_token: Activations for each token [vocab_size, hidden_dim].
        U_null: Null space basis [hidden_dim, null_rank].
        backend: Backend for tensor operations.

    Returns:
        Scores [vocab_size] where higher = activates more null space directions.
    """
    b = backend

    acts = activations_by_token
    # Normalize each activation to unit norm (direction only)
    eps = regularization_epsilon(b, acts)
    norms = b.sqrt(b.sum(acts * acts, axis=1, keepdims=True) + eps)
    acts = acts / norms
    b.eval(acts)

    # Project each token's activation onto null space
    # projections[i] = U_null.T @ activations[i] -> [null_rank]
    # We want: activations @ U_null -> [vocab_size, null_rank]
    projections = b.matmul(acts, U_null)
    b.eval(projections)

    # Score = L2 norm of projection (how much this token activates null directions)
    scores = b.sqrt(b.sum(projections * projections, axis=1))
    b.eval(scores)

    return scores


def find_null_space_tokens_closed_form(
    model: Any,
    U_null: "Array",
    layer_idx: int,
    backend: "Backend",
) -> list[tuple[int, float]]:
    """Find tokens that activate null space directions - CLOSED FORM.

    Instead of gradient ascent, we:
    1. Forward ALL tokens through the model to target layer
    2. Normalize activations to unit vectors (direction only)
    3. Score each token by ||U_null.T @ activation||
    4. Select top-k tokens

    This is O(vocab_size) forward passes (batched), but:
    - Deterministic
    - No iteration
    - Guaranteed to find best tokens in vocabulary

    Args:
        model: The model.
        U_null: Null space basis [hidden_dim, null_rank].
        layer_idx: Target layer for activations.
        backend: Backend for tensor operations.

    Returns:
        List of (token_id, score) tuples, sorted by score descending.
    """
    b = backend
    logger.info("CLOSED-FORM TOKEN SCORING: Starting for layer %d...", layer_idx)

    try:
        # Get model internals
        inner = model.model if hasattr(model, "model") else model

        if hasattr(inner, "embed_tokens"):
            embed_weight = inner.embed_tokens.weight
            logger.info("CLOSED-FORM: Found embed_tokens")
        elif hasattr(inner, "wte"):
            embed_weight = inner.wte.weight
            logger.info("CLOSED-FORM: Found wte")
        else:
            logger.error("CLOSED-FORM: Cannot find embedding layer")
            raise RuntimeError("Cannot find embedding layer")

        vocab_size = int(b.shape(embed_weight)[0])
        hidden_dim = int(b.shape(U_null)[0])
        null_rank = int(b.shape(U_null)[1])
        if null_rank <= 0:
            logger.info("CLOSED-FORM TOKEN SCORING: No null space available")
            return []

        batch_size = min(vocab_size, max(1, hidden_dim))

        logger.info(
            "CLOSED-FORM TOKEN SCORING: Scoring %d tokens for layer %d (batch=%d, null_rank=%d)",
            vocab_size,
            layer_idx,
            batch_size,
            null_rank,
        )

        all_scores: list[float] = []

        # Process vocabulary in batches
        for start in range(0, vocab_size, batch_size):
            end = min(start + batch_size, vocab_size)
            batch_tokens = list(range(start, end))

            # Get embeddings for this batch
            token_indices = b.array(batch_tokens, dtype="int32")
            embeddings = b.take(embed_weight, token_indices, axis=0)  # [batch, embed_dim]
            b.eval(embeddings)

            # Forward through layers to target layer
            # We need to process each token as a single-token sequence
            h = b.expand_dims(embeddings, axis=1)  # [batch, 1, embed_dim]

            for idx, layer in enumerate(inner.layers):
                if idx > layer_idx:
                    break
                result = layer(h)
                if isinstance(result, tuple):
                    h = result[0]
                else:
                    h = result

            # h is now [batch, 1, hidden_dim]
            # Squeeze to [batch, hidden_dim]
            activations = b.squeeze(h, axis=1)
            b.eval(activations)

            # Score against null space (normalized to compare directions, not magnitudes)
            scores = score_tokens_for_null_space(activations, U_null, b)
            b.eval(scores)

            batch_scores = b.tolist(scores)
            all_scores.extend(batch_scores)

            if (end - start) == batch_size and end < vocab_size:
                logger.debug(
                    "CLOSED-FORM: Processed %d/%d tokens (%.1f%%)",
                    end,
                    vocab_size,
                    100.0 * end / vocab_size,
                )

        if not all_scores:
            logger.warning("CLOSED-FORM TOKEN SCORING: No scores computed")
            return []

        max_score = max(all_scores)
        score_eps = regularization_epsilon(b, U_null)
        if max_score <= score_eps:
            logger.info("CLOSED-FORM TOKEN SCORING: No numerically significant scores")
            return []

        threshold = max_score * sqrt_scalar(machine_epsilon(b, U_null), b)
        scored_tokens = [
            (token_id, score)
            for token_id, score in enumerate(all_scores)
            if score >= threshold
        ]
        scored_tokens.sort(key=lambda item: item[1], reverse=True)

        limit = min(null_rank, len(scored_tokens))
        if limit <= 0:
            return []

        top_tokens = scored_tokens[:limit]

        logger.info(
            "CLOSED-FORM TOKEN SCORING: Selected %d tokens (threshold=%.3e, max=%.3e)",
            len(top_tokens),
            threshold,
            max_score,
        )

        return top_tokens

    except Exception as e:
        logger.error("CLOSED-FORM TOKEN SCORING FAILED: %s: %s", type(e).__name__, e)
        import traceback
        logger.error("TRACEBACK:\n%s", traceback.format_exc())
        raise


def augment_rank_closed_form(
    model: Any,
    tokenizer: Any,
    activations: "Array",
    layer_idx: int,
    backend: "Backend",
) -> RankAugmentationResult:
    """Augment activation rank using closed-form token selection.

    This replaces gradient ascent with:
    1. Compute null space of current activations
    2. Score ALL tokens by null space projection (closed-form)
    3. Add best tokens until target rank achieved

    Args:
        model: The model.
        tokenizer: Tokenizer for decoding.
        activations: Current activations [n_samples, hidden_dim].
        layer_idx: Target layer.
        backend: Backend for tensor operations.

    Returns:
        RankAugmentationResult with generation statistics.
    """
    b = backend
    current_acts = _promote_precision(activations, b)
    b.eval(current_acts)

    initial_rank, hidden_dim = compute_numerical_rank(current_acts, b)

    target_rank = hidden_dim

    logger.info(
        "CLOSED-FORM RANK AUGMENTATION: Starting at rank %d/%d, target=%d",
        initial_rank,
        hidden_dim,
        target_rank,
    )

    if initial_rank >= target_rank:
        logger.info("CLOSED-FORM: Already at target rank!")
        return RankAugmentationResult(
            initial_rank=initial_rank,
            final_rank=initial_rank,
            hidden_dim=hidden_dim,
            probes_generated=0,
            iterations=1,
            full_rank_achieved=initial_rank >= hidden_dim,
            generated_probes=[],
        )

    generated_probes: list[OrthogonalProbeResult] = []
    current_rank = initial_rank
    iteration = 0
    max_iterations = hidden_dim  # At most one rank gain per iteration

    while current_rank < target_rank and iteration < max_iterations:
        iteration += 1

        # Compute null space
        U_null = compute_null_space_basis(current_acts, current_rank, b)
        if U_null is None:
            logger.info("CLOSED-FORM: No null space remaining")
            break

        null_dim = int(b.shape(U_null)[1])
        logger.info(
            "CLOSED-FORM: Iteration %d, rank=%d/%d, null_dim=%d",
            iteration,
            current_rank,
            target_rank,
            null_dim,
        )

        # Find best tokens for null space (closed-form)
        top_tokens = find_null_space_tokens_closed_form(
            model=model,
            U_null=U_null,
            layer_idx=layer_idx,
            backend=b,
        )

        if not top_tokens:
            logger.warning("CLOSED-FORM: No tokens found")
            break

        # Add top tokens and their activations
        new_activations = []
        for token_id, score in top_tokens:
            # Get activation for this single token
            token_input = b.array([[token_id]], dtype="int32")
            b.eval(token_input)

            # Forward to get activation
            inner = model.model if hasattr(model, "model") else model
            if hasattr(inner, "embed_tokens"):
                h = inner.embed_tokens(token_input)
            elif hasattr(inner, "wte"):
                h = inner.wte(token_input)
            else:
                continue

            for idx, layer in enumerate(inner.layers):
                if idx > layer_idx:
                    break
                result = layer(h)
                if isinstance(result, tuple):
                    h = result[0]
                else:
                    h = result

            # Mean pool (single token, so just squeeze)
            activation = b.squeeze(h, axis=(0, 1))
            b.eval(activation)
            new_activations.append(activation)

            # Decode token
            try:
                text = tokenizer.decode([token_id])
            except Exception:
                text = f"<token-{token_id}>"

            generated_probes.append(
                OrthogonalProbeResult(
                    token_ids=[token_id],
                    text=text,
                    orthogonal_component_norm=score,
                )
            )

            # Check if we've reached target rank
            if len(new_activations) >= null_dim:
                break

        if new_activations:
            # Stack and concatenate
            new_acts_stacked = b.stack(new_activations, axis=0)
            b.eval(new_acts_stacked)
            current_acts = b.concatenate([current_acts, new_acts_stacked], axis=0)
            b.eval(current_acts)

        # Check new rank
        new_rank, _ = compute_numerical_rank(current_acts, b)
        rank_increase = new_rank - current_rank

        logger.info(
            "CLOSED-FORM: Added %d tokens, rank %d -> %d (+%d)",
            len(new_activations),
            current_rank,
            new_rank,
            rank_increase,
        )

        if rank_increase == 0:
            logger.warning("CLOSED-FORM: No rank increase, stopping")
            break

        current_rank = new_rank

    final_rank, _ = compute_numerical_rank(current_acts, b)
    full_rank_achieved = final_rank >= hidden_dim

    logger.info(
        "CLOSED-FORM RANK AUGMENTATION: Complete. rank=%d/%d (%.1f%%), "
        "generated=%d probes in %d iterations",
        final_rank,
        hidden_dim,
        100.0 * final_rank / hidden_dim,
        len(generated_probes),
        iteration,
    )

    return RankAugmentationResult(
        initial_rank=initial_rank,
        final_rank=final_rank,
        hidden_dim=hidden_dim,
        probes_generated=len(generated_probes),
        iterations=iteration,
        full_rank_achieved=full_rank_achieved,
        generated_probes=generated_probes,
    )
def find_null_space_sequences(
    model: Any,
    tokenizer: Any,
    U_null: "Array",
    layer_idx: int,
    backend: "Backend",
) -> list[SequenceProbeResult]:
    """Find token sequences that activate null-space directions.

    Closed-form approach:
    1. Score all vocab tokens by ||U_null^T @ activation||
    2. Select numerically significant tokens up to null-space rank
    3. Return single-token sequences (deterministic, no optimization)

    Args:
        model: The model (must have .model with .embed_tokens/.wte and .layers).
        tokenizer: Tokenizer for decoding.
        U_null: Null space basis [hidden_dim, null_rank] from compute_null_space_basis.
        layer_idx: Target layer for null-space activation.
        backend: Backend for tensor operations.

    Returns:
        List of SequenceProbeResult, sorted by null_space_norm descending.
        Each result contains the token sequence and activation metrics.

    Example:
        >>> U_null = compute_null_space_basis(activations, rank, backend)
        >>> sequences = find_null_space_sequences(
        ...     model, tokenizer, U_null, layer_idx=0, backend=backend
        ... )
        >>> for seq in sequences[:10]:
        ...     print(f"'{seq.text}': null_norm={seq.null_space_norm:.4f}")
    """
    b = backend
    logger.info(
        "SEQUENCE PROBE: Closed-form token scoring for layer %d",
        layer_idx,
    )

    top_tokens = find_null_space_tokens_closed_form(
        model=model,
        U_null=U_null,
        layer_idx=layer_idx,
        backend=b,
    )

    if not top_tokens:
        logger.warning("SEQUENCE PROBE: No tokens found in vocabulary scan")
        return []

    results: list[SequenceProbeResult] = []
    for seed_token_id, seed_score in top_tokens:
        try:
            text = tokenizer.decode([seed_token_id], skip_special_tokens=True)
        except Exception:
            text = f"<tokens:{[seed_token_id]}>"

        results.append(
            SequenceProbeResult(
                token_ids=[seed_token_id],
                text=text,
                null_space_norm=seed_score,
                seed_token_id=seed_token_id,
                gradient_steps=0,
                improvement_ratio=1.0,
            )
        )

    if results:
        best = results[0].null_space_norm
        worst = results[-1].null_space_norm
        mean_norm = sum(r.null_space_norm for r in results) / len(results)
        logger.info(
            "SEQUENCE PROBE: %d tokens selected (best=%.4f, worst=%.4f, mean=%.4f)",
            len(results),
            best,
            worst,
            mean_norm,
        )

    return results


def find_null_space_texts(
    model: Any,
    tokenizer: Any,
    U_null: "Array",
    layer_idx: int,
    backend: "Backend",
) -> list[str]:
    """Convenience wrapper that returns decoded text strings.

    Same as find_null_space_sequences but returns just the text strings,
    suitable for direct use in rank augmentation.

    Args:
        model: The model.
        tokenizer: Tokenizer for decoding.
        U_null: Null space basis [hidden_dim, null_rank].
        layer_idx: Target layer for null-space activation.
        backend: Backend for tensor operations.

    Returns:
        List of decoded text strings that activate null-space directions.
    """
    sequences = find_null_space_sequences(
        model=model,
        tokenizer=tokenizer,
        U_null=U_null,
        layer_idx=layer_idx,
        backend=backend,
    )

    # Return unique, non-empty texts
    texts: list[str] = []
    seen: set[str] = set()

    for seq in sequences:
        text = seq.text.strip()
        if text and text not in seen:
            seen.add(text)
            texts.append(text)

    return texts


# =============================================================================
# TRAJECTORY-BASED NULL-SPACE DISCOVERY
# =============================================================================
# Trajectories capture the DYNAMICS of information flow through the model.
# A forward pass through text produces a trajectory - a sequence of activations
# as context builds. The trajectory's geometry (positions, velocities) spans
# far more of the activation space than individual token activations.
#
# Key insight: The trajectory's tangent space (velocities) captures directions
# the model USES to process information flow. These are directions we should
# NOT project into. The orthogonal complement is the true null-space.
# =============================================================================


@dataclass
class TrajectoryResult:
    """Result of collecting a trajectory through the model.

    A trajectory is the sequence of activations as context builds token-by-token.
    Includes positions (raw activations) and velocities (first differences).
    """

    positions: "Array"  # [seq_len, hidden_dim] - raw activations per position
    velocities: "Array"  # [seq_len-1, hidden_dim] - first differences
    accelerations: "Array | None"  # [seq_len-2, hidden_dim] - second differences (optional)
    seq_len: int
    hidden_dim: int
    text: str  # Original text (for debugging)


@dataclass
class TrajectorySubspaceResult:
    """Result of computing the subspace spanned by trajectories."""

    Vt: "Array"  # Right singular vectors [min(n,d), hidden_dim]
    singular_values: "Array"  # Singular values
    rank: int  # Numerical rank
    hidden_dim: int
    total_samples: int  # Total trajectory points used
    position_contribution: int  # Samples from positions
    velocity_contribution: int  # Samples from velocities


def collect_trajectory(
    model: Any,
    tokenizer: Any,
    text: str,
    layer_idx: int,
    backend: "Backend",
    include_accelerations: bool = False,
) -> TrajectoryResult | None:
    """Collect activation trajectory for a full text sequence at a specific layer.

    A single forward pass gives the full trajectory - the sequence of hidden states
    as context accumulates. This captures HOW the model processes information flow,
    not just WHERE it lands.

    Args:
        model: The model to collect activations from.
        tokenizer: Tokenizer for encoding text.
        text: Input text to process.
        layer_idx: Layer index to collect activations from.
        backend: Backend for tensor operations.
        include_accelerations: If True, also compute second differences.

    Returns:
        TrajectoryResult with positions, velocities, and optional accelerations.
        Returns None if collection fails.
    """
    b = backend
    logger.debug("TRAJECTORY: Collecting for layer %d, text='%s...'", layer_idx, text[:30])

    try:
        # Get model internals
        inner = model.model if hasattr(model, "model") else model

        if not hasattr(inner, "layers"):
            logger.warning("TRAJECTORY: Model has no layers attribute")
            return None

        # Tokenize
        tokens = tokenizer.encode(text, add_special_tokens=True)
        if isinstance(tokens, list):
            token_ids = tokens
        else:
            token_ids = list(tokens.ids)

        if len(token_ids) < 2:
            logger.debug("TRAJECTORY: Text too short (need >= 2 tokens)")
            return None

        # Create input tensor
        input_ids = b.array([token_ids])
        b.eval(input_ids)

        # Get embeddings
        if hasattr(inner, "embed_tokens"):
            h = inner.embed_tokens(input_ids)
        elif hasattr(inner, "wte"):
            h = inner.wte(input_ids)
        else:
            logger.warning("TRAJECTORY: Cannot find embedding layer")
            return None

        b.eval(h)

        # Forward through layers up to target
        for idx, layer in enumerate(inner.layers):
            if idx > layer_idx:
                break
            result = layer(h)
            if isinstance(result, tuple):
                h = result[0]
            else:
                h = result

        b.eval(h)

        # h is now [batch=1, seq_len, hidden_dim]
        # Squeeze batch dimension to get [seq_len, hidden_dim]
        positions = b.squeeze(h, axis=0)
        b.eval(positions)

        seq_len = int(b.shape(positions)[0])
        hidden_dim = int(b.shape(positions)[1])

        # Compute velocities: first differences along sequence
        # velocities[i] = positions[i+1] - positions[i]
        pos_shifted = positions[1:, :]  # [seq_len-1, hidden_dim]
        pos_base = positions[:-1, :]  # [seq_len-1, hidden_dim]
        velocities = pos_shifted - pos_base
        b.eval(velocities)

        # Optionally compute accelerations
        accelerations = None
        if include_accelerations and seq_len >= 3:
            vel_shifted = velocities[1:, :]  # [seq_len-2, hidden_dim]
            vel_base = velocities[:-1, :]  # [seq_len-2, hidden_dim]
            accelerations = vel_shifted - vel_base
            b.eval(accelerations)

        return TrajectoryResult(
            positions=positions,
            velocities=velocities,
            accelerations=accelerations,
            seq_len=seq_len,
            hidden_dim=hidden_dim,
            text=text,
        )
    except Exception as e:
        logger.warning("TRAJECTORY: Collection failed for '%s...': %s", text[:30], e)
        return None


def _model_max_seq_len(model: Any) -> int | None:
    """Extract maximum sequence length from model metadata, if available."""
    inner = model.model if hasattr(model, "model") else model
    candidates = [
        getattr(inner, "max_seq_len", None),
        getattr(inner, "max_seq_length", None),
        getattr(getattr(inner, "config", None), "max_position_embeddings", None),
        getattr(getattr(inner, "config", None), "max_seq_len", None),
        getattr(getattr(inner, "config", None), "max_seq_length", None),
    ]
    for value in candidates:
        if isinstance(value, int) and value > 0:
            return value
    return None


def compute_trajectory_subspace(
    trajectories: list[TrajectoryResult],
    backend: "Backend",
    include_velocities: bool = True,
    include_accelerations: bool = False,
) -> TrajectorySubspaceResult | None:
    """Compute the subspace spanned by trajectory dynamics.

    This captures not just WHERE the model goes, but HOW it gets there.
    Velocities capture the directions the model uses to flow between concepts.

    Args:
        trajectories: List of TrajectoryResult objects.
        backend: Backend for tensor operations.
        include_velocities: If True, include first differences in subspace.
        include_accelerations: If True, include second differences in subspace.

    Returns:
        TrajectorySubspaceResult with SVD decomposition and rank.
        Returns None if computation fails.
    """
    b = backend

    if not trajectories:
        logger.warning("TRAJECTORY SUBSPACE: No trajectories provided")
        return None

    logger.info(
        "TRAJECTORY SUBSPACE: Computing from %d trajectories (velocities=%s, accelerations=%s)",
        len(trajectories), include_velocities, include_accelerations
    )

    try:
        # Collect all trajectory features
        all_features: list["Array"] = []
        position_count = 0
        velocity_count = 0

        for traj in trajectories:
            # Always include positions
            all_features.append(traj.positions)
            position_count += int(b.shape(traj.positions)[0])

            if include_velocities:
                all_features.append(traj.velocities)
                velocity_count += int(b.shape(traj.velocities)[0])

            if include_accelerations and traj.accelerations is not None:
                all_features.append(traj.accelerations)

        # Stack all features: [total_points, hidden_dim]
        X = b.concatenate(all_features, axis=0)
        X = _promote_precision(X, b)
        b.eval(X)

        total_samples = int(b.shape(X)[0])
        hidden_dim = int(b.shape(X)[1])

        logger.info(
            "TRAJECTORY SUBSPACE: X shape [%d, %d] (positions=%d, velocities=%d)",
            total_samples, hidden_dim, position_count, velocity_count
        )

        # For tall-skinny matrices (m >> n), use Gram matrix trick:
        # G = X.T @ X has shape [n, n] instead of [m, n]
        # Eigenvalues of G = singular_values² of X
        # Eigenvectors of G = right singular vectors (V) of X
        # This avoids computing the full m×m U matrix which would exceed memory
        if total_samples > hidden_dim * 2:
            logger.info(
                "TRAJECTORY SUBSPACE: Using Gram matrix trick (m=%d >> n=%d)",
                total_samples, hidden_dim
            )
            # G = X.T @ X is [hidden_dim, hidden_dim]
            G = b.matmul(b.transpose(X), X)
            b.eval(G)

            # Eigendecomposition: G = V @ diag(eigenvalues) @ V.T
            eigenvalues, V = b.eigh(G)
            b.eval(eigenvalues, V)

            # Singular values = sqrt(eigenvalues), sorted descending
            # eigenvalues from eigh are in ascending order, so reverse
            n = int(b.shape(eigenvalues)[0])
            reverse_idx = b.arange(n - 1, -1, -1)
            eigenvalues = b.take(eigenvalues, reverse_idx, axis=0)
            V = b.take(V, reverse_idx, axis=1)
            b.eval(eigenvalues, V)

            # Clamp negative eigenvalues to zero (numerical noise)
            eigenvalues = b.maximum(eigenvalues, b.zeros_like(eigenvalues))
            S = b.sqrt(eigenvalues)
            b.eval(S)

            # V is [hidden_dim, hidden_dim], Vt = V.T
            Vt = b.transpose(V)
            b.eval(Vt)
        else:
            # Standard SVD for wide or square matrices
            logger.info("TRAJECTORY SUBSPACE: Using standard SVD")
            _, S, Vt = b.svd(X, full_matrices=False)
            b.eval(S, Vt)

        # Compute numerical rank using threshold sigma_max * sqrt(eps)
        eps = machine_epsilon(b, X)
        threshold_factor = sqrt_scalar(eps, b)

        max_s_arr = b.max(S)
        b.eval(max_s_arr)
        max_s = float(b.to_scalar(max_s_arr))
        threshold = max_s * threshold_factor

        # Count singular values above threshold
        rank_mask = S > threshold
        rank_arr = b.sum(b.astype(rank_mask, "int32"))
        b.eval(rank_arr)
        rank = int(b.to_scalar(rank_arr))

        logger.info(
            "TRAJECTORY SUBSPACE: rank=%d/%d (%.1f%% coverage), sigma_max=%.4e, threshold=%.4e",
            rank, hidden_dim, 100.0 * rank / hidden_dim, max_s, threshold
        )

        return TrajectorySubspaceResult(
            Vt=Vt,
            singular_values=S,
            rank=rank,
            hidden_dim=hidden_dim,
            total_samples=total_samples,
            position_contribution=position_count,
            velocity_contribution=velocity_count,
        )

    except Exception as e:
        logger.error("TRAJECTORY SUBSPACE: Computation failed: %s", e)
        import traceback
        logger.error("TRACEBACK:\n%s", traceback.format_exc())
        return None


def compute_trajectory_null_space(
    subspace_result: TrajectorySubspaceResult,
    backend: "Backend",
) -> "Array | None":
    """Compute the null space from trajectory subspace.

    The null space consists of directions orthogonal to ALL trajectory dynamics.
    These are the directions the model doesn't use for information flow -
    the safe directions for null-space projection.

    Args:
        subspace_result: Result from compute_trajectory_subspace.
        backend: Backend for tensor operations.

    Returns:
        Null space basis [hidden_dim, null_rank], or None if already full rank.
    """
    b = backend

    rank = subspace_result.rank
    hidden_dim = subspace_result.hidden_dim
    Vt = subspace_result.Vt

    null_rank = hidden_dim - rank

    if null_rank <= 0:
        logger.info("TRAJECTORY NULL SPACE: Trajectories already span full space")
        return None

    logger.info(
        "TRAJECTORY NULL SPACE: rank=%d, null_rank=%d (%.1f%% available)",
        rank, null_rank, 100.0 * null_rank / hidden_dim
    )

    # Null space is spanned by Vt[rank:].T
    # Vt has shape [min(n,d), hidden_dim]
    # We want the directions NOT covered by the first `rank` singular vectors
    Vt_null = Vt[rank:, :]  # [null_rank, hidden_dim]
    b.eval(Vt_null)

    # Return as [hidden_dim, null_rank] to match compute_null_space_basis convention
    U_null = b.transpose(Vt_null)  # [hidden_dim, null_rank]
    b.eval(U_null)

    return U_null


def collect_trajectories_batch(
    model: Any,
    tokenizer: Any,
    texts: list[str],
    layer_idx: int,
    backend: "Backend",
    include_accelerations: bool = False,
) -> list[TrajectoryResult]:
    """Collect trajectories for multiple texts efficiently.

    Args:
        model: The model to collect activations from.
        tokenizer: Tokenizer for encoding text.
        texts: List of input texts to process.
        layer_idx: Layer index to collect activations from.
        backend: Backend for tensor operations.
        include_accelerations: If True, also compute second differences.

    Returns:
        List of TrajectoryResult objects (may be shorter than texts if some fail).
    """
    results: list[TrajectoryResult] = []
    max_seq_len = _model_max_seq_len(model)

    for text in texts:
        # Truncate very long texts
        tokens = tokenizer.encode(text, add_special_tokens=True)
        if isinstance(tokens, list):
            token_ids = tokens
        else:
            token_ids = list(tokens.ids)

        if max_seq_len is not None and len(token_ids) > max_seq_len:
            # Truncate and decode back to text
            truncated_ids = token_ids[:max_seq_len]
            text = tokenizer.decode(truncated_ids, skip_special_tokens=True)

        traj = collect_trajectory(
            model=model,
            tokenizer=tokenizer,
            text=text,
            layer_idx=layer_idx,
            backend=backend,
            include_accelerations=include_accelerations,
        )

        if traj is not None:
            results.append(traj)

    logger.info(
        "TRAJECTORY BATCH: Collected %d/%d trajectories for layer %d",
        len(results), len(texts), layer_idx
    )

    return results


def find_trajectory_null_space(
    model: Any,
    tokenizer: Any,
    probe_texts: list[str],
    layer_idx: int,
    backend: "Backend",
    include_velocities: bool = True,
    include_accelerations: bool = False,
) -> tuple["Array | None", TrajectorySubspaceResult | None]:
    """High-level function to find null space from trajectory probing.

    This is the main entry point for trajectory-based null-space discovery.
    It collects trajectories, computes the subspace they span, and returns
    the orthogonal complement (null space).

    Args:
        model: The model to analyze.
        tokenizer: Tokenizer for encoding text.
        probe_texts: List of probe texts to use for trajectory collection.
        layer_idx: Layer index to analyze.
        backend: Backend for tensor operations.
        include_velocities: If True, include first differences.
        include_accelerations: If True, include second differences.

    Returns:
        Tuple of (U_null, subspace_result) where:
        - U_null: Null space basis [hidden_dim, null_rank], or None if full rank
        - subspace_result: TrajectorySubspaceResult with diagnostic info
    """
    b = backend

    logger.info(
        "TRAJECTORY NULL SPACE: Finding for layer %d with %d probes",
        layer_idx, len(probe_texts)
    )

    # Collect trajectories
    trajectories = collect_trajectories_batch(
        model=model,
        tokenizer=tokenizer,
        texts=probe_texts,
        layer_idx=layer_idx,
        backend=b,
        include_accelerations=include_accelerations,
    )

    if not trajectories:
        logger.warning("TRAJECTORY NULL SPACE: No trajectories collected")
        return None, None

    # Compute subspace
    subspace_result = compute_trajectory_subspace(
        trajectories=trajectories,
        backend=b,
        include_velocities=include_velocities,
        include_accelerations=include_accelerations,
    )

    if subspace_result is None:
        logger.warning("TRAJECTORY NULL SPACE: Subspace computation failed")
        return None, None

    # Compute null space
    U_null = compute_trajectory_null_space(subspace_result, b)

    return U_null, subspace_result


# =============================================================================
# TRAJECTORY-TANGENT NULL-SPACE PROJECTION
# =============================================================================
# Key insight: Not all null-space directions are equal. Knowledge should be
# injected into null-space directions that are TANGENT to the trajectory -
# "along the road the model already uses."
#
# Velocities show WHERE the trajectory is heading. Null-space directions
# aligned with velocities are the "shoulders of the road" - unused capacity
# that's still reachable by the model's natural information flow.
#
# This is the difference between:
# - Building a town in the middle of nowhere (random null-space)
# - Building a town along the highway (trajectory-tangent null-space)
# =============================================================================


@dataclass
class TrajectoryTangentResult:
    """Result of trajectory-tangent null-space computation.

    Contains both the full null space and the trajectory-tangent subspace
    within it - directions where knowledge can be injected "along the road."
    """

    U_null: "Array"  # Full null space [hidden_dim, null_rank]
    U_tangent: "Array"  # Trajectory-tangent null space [hidden_dim, tangent_rank]
    null_rank: int  # Rank of full null space
    tangent_rank: int  # Rank of tangent subspace (tangent_rank <= null_rank)
    velocity_alignment: float  # Mean alignment of tangent with velocities (0-1)
    hidden_dim: int


def compute_trajectory_tangent_null_space(
    trajectories: list[TrajectoryResult],
    backend: "Backend",
    subspace_result: TrajectorySubspaceResult | None = None,
) -> TrajectoryTangentResult | None:
    """Compute null space directions that are tangent to trajectory flow.

    The key insight: velocities show which directions the model uses to FLOW
    between concepts. Null-space directions aligned with velocities are
    "adjacent to the road" - unused but reachable.

    Algorithm:
    1. Compute full trajectory subspace (positions + velocities)
    2. Get null space (orthogonal complement)
    3. Project velocities into null space to find "road extensions"
    4. SVD on projected velocities to get dominant tangent directions

    Args:
        trajectories: List of TrajectoryResult objects.
        backend: Backend for tensor operations.
        subspace_result: Optional precomputed TrajectorySubspaceResult to
            avoid recomputing the SVD.

    Returns:
        TrajectoryTangentResult with null space and tangent directions.
        Returns None if computation fails.
    """
    b = backend

    if not trajectories:
        logger.warning("TRAJECTORY TANGENT: No trajectories provided")
        return None

    logger.info(
        "TRAJECTORY TANGENT: Computing from %d trajectories",
        len(trajectories)
    )

    try:
        # Step 1: Compute trajectory subspace (positions + velocities)
        if subspace_result is None:
            subspace_result = compute_trajectory_subspace(
                trajectories=trajectories,
                backend=b,
                include_velocities=True,
                include_accelerations=False,
            )

            if subspace_result is None:
                logger.warning("TRAJECTORY TANGENT: Subspace computation failed")
                return None

        rank = subspace_result.rank
        hidden_dim = subspace_result.hidden_dim
        Vt = subspace_result.Vt

        null_rank = hidden_dim - rank
        if null_rank <= 0:
            logger.info("TRAJECTORY TANGENT: No null space (full rank)")
            return None

        # Step 2: Get null space basis
        # Null space is spanned by Vt[rank:].T
        U_null = b.transpose(Vt[rank:, :])  # [hidden_dim, null_rank]
        U_null = _promote_precision(U_null, b)
        b.eval(U_null)

        # Step 3: Stack all velocities
        all_velocities: list["Array"] = []
        for traj in trajectories:
            all_velocities.append(traj.velocities)

        velocities = b.concatenate(all_velocities, axis=0)  # [n_vel, hidden_dim]
        velocities = _promote_precision(velocities, b)
        b.eval(velocities)

        n_vel = int(b.shape(velocities)[0])

        # Step 4: Project velocities into null space
        # velocity_in_null[i] = U_null @ U_null.T @ velocity[i]
        # This gives the component of each velocity that lies in null space
        velocity_null_proj = b.matmul(
            b.matmul(velocities, U_null),  # [n_vel, null_rank]
            b.transpose(U_null)  # [null_rank, hidden_dim]
        )  # [n_vel, hidden_dim]
        b.eval(velocity_null_proj)

        # Step 5: SVD on velocity projections to find dominant tangent directions
        # These are the null-space directions most aligned with velocity flow
        U_tan, S_tan, Vt_tan = b.svd(velocity_null_proj, compute_uv=True)
        b.eval(U_tan, S_tan, Vt_tan)

        # Step 6: Determine tangent rank (significant velocity projections)
        eps = machine_epsilon(b, S_tan)
        threshold_factor = sqrt_scalar(eps, b)

        max_s_arr = b.max(S_tan)
        b.eval(max_s_arr)
        max_s = float(b.to_scalar(max_s_arr))

        if max_s < eps:
            logger.info(
                "TRAJECTORY TANGENT: Velocities don't project into null space "
                "(max_singular=%.4e). No tangent subspace.",
                max_s,
            )
            return None

        threshold = max_s * threshold_factor
        rank_mask = S_tan > threshold
        tangent_rank_arr = b.sum(b.astype(rank_mask, "int32"))
        b.eval(tangent_rank_arr)
        tangent_rank = int(b.to_scalar(tangent_rank_arr))

        if tangent_rank <= 0:
            logger.info(
                "TRAJECTORY TANGENT: No singular values above threshold (%.4e).",
                threshold,
            )
            return None

        # Clamp to null_rank
        tangent_rank = min(tangent_rank, null_rank)

        # Step 7: Extract tangent basis
        # Vt_tan contains right singular vectors - directions in hidden_dim space
        # The first tangent_rank rows of Vt_tan are the dominant tangent directions
        U_tangent = b.transpose(Vt_tan[:tangent_rank, :])  # [hidden_dim, tangent_rank]
        b.eval(U_tangent)

        # Step 8: Compute alignment metric
        # How well do the tangent directions capture velocity projections?
        total_var = b.sum(S_tan * S_tan)
        captured_var = b.sum(S_tan[:tangent_rank] * S_tan[:tangent_rank])
        b.eval(total_var, captured_var)

        total_var_val = float(b.to_scalar(total_var))
        captured_var_val = float(b.to_scalar(captured_var))

        if total_var_val > 0:
            velocity_alignment = captured_var_val / total_var_val
        else:
            velocity_alignment = 0.0

        logger.info(
            "TRAJECTORY TANGENT: null_rank=%d, tangent_rank=%d (%.1f%%), "
            "velocity_alignment=%.4f",
            null_rank, tangent_rank,
            100.0 * tangent_rank / null_rank if null_rank > 0 else 0,
            velocity_alignment
        )

        return TrajectoryTangentResult(
            U_null=U_null,
            U_tangent=U_tangent,
            null_rank=null_rank,
            tangent_rank=tangent_rank,
            velocity_alignment=velocity_alignment,
            hidden_dim=hidden_dim,
        )

    except Exception as e:
        logger.error("TRAJECTORY TANGENT: Computation failed: %s", e)
        import traceback
        logger.error("TRACEBACK:\n%s", traceback.format_exc())
        return None


def project_delta_to_trajectory_tangent(
    delta: "Array",
    tangent_result: TrajectoryTangentResult,
    backend: "Backend",
    use_full_null: bool = False,
) -> "Array":
    """Project weight delta into trajectory-tangent null space.

    This puts the delta "along the road" - in null-space directions that
    are aligned with the model's natural trajectory flow.

    Args:
        delta: Weight delta to project [out_dim, in_dim] or [in_dim].
        tangent_result: Result from compute_trajectory_tangent_null_space.
        backend: Backend for tensor operations.
        use_full_null: If True, use full null space instead of tangent subspace.
            Useful for comparison or fallback.

    Returns:
        Projected delta in the same shape as input.
    """
    b = backend

    delta = b.array(delta)
    delta = _promote_precision(delta, b)
    b.eval(delta)

    # Choose projection basis
    if use_full_null:
        U = tangent_result.U_null
        label = "null"
    else:
        U = tangent_result.U_tangent
        label = "tangent"

    U = _promote_precision(U, b)
    b.eval(U)

    original_shape = b.shape(delta)
    is_2d = len(original_shape) == 2

    if is_2d:
        # Weight matrix [out_dim, in_dim]
        # Project along input dimension: delta @ U @ U.T
        # This projects each row (output neuron's input weights) into tangent space
        out_dim = int(original_shape[0])
        in_dim = int(original_shape[1])

        if in_dim != tangent_result.hidden_dim:
            logger.warning(
                "TRAJECTORY TANGENT PROJECT: Dimension mismatch "
                "(delta in_dim=%d, hidden_dim=%d). Returning original.",
                in_dim, tangent_result.hidden_dim
            )
            return delta

        # P = U @ U.T is the projection matrix [hidden_dim, hidden_dim]
        # delta_proj = delta @ P = delta @ U @ U.T
        delta_proj = b.matmul(
            b.matmul(delta, U),  # [out_dim, rank]
            b.transpose(U)  # [rank, hidden_dim]
        )  # [out_dim, hidden_dim]
        b.eval(delta_proj)

    else:
        # Vector [in_dim]
        in_dim = int(original_shape[0])

        if in_dim != tangent_result.hidden_dim:
            logger.warning(
                "TRAJECTORY TANGENT PROJECT: Dimension mismatch "
                "(delta dim=%d, hidden_dim=%d). Returning original.",
                in_dim, tangent_result.hidden_dim
            )
            return delta

        # P @ delta = U @ U.T @ delta
        delta_proj = b.matmul(U, b.matmul(b.transpose(U), delta))
        b.eval(delta_proj)

    # Compute norms for logging
    original_norm = b.sqrt(b.sum(delta * delta))
    projected_norm = b.sqrt(b.sum(delta_proj * delta_proj))
    b.eval(original_norm, projected_norm)

    orig_val = float(b.to_scalar(original_norm))
    proj_val = float(b.to_scalar(projected_norm))

    if orig_val > 0:
        preserved = proj_val / orig_val
    else:
        preserved = 0.0

    logger.debug(
        "TRAJECTORY TANGENT PROJECT (%s): ||delta||=%.4f, ||projected||=%.4f, "
        "preserved=%.2f%%",
        label, orig_val, proj_val, preserved * 100
    )

    return delta_proj


def project_delta_to_variance_null_space(
    delta: "Array",
    variance_result: VarianceNullSpaceResult,
    backend: "Backend",
) -> "Array":
    """Project weight delta into low-variance (available) directions.

    This projects source delta into directions where the target has low
    activation variance - the "available" capacity for new knowledge.

    Based on LoRA-Null (AAAI 2026): "The null space of activations is more accurate."

    Args:
        delta: Weight delta to project [out_dim, in_dim] or [in_dim].
        variance_result: Result from compute_variance_null_space.
        backend: Backend for tensor operations.

    Returns:
        Projected delta in the same shape as input.
    """
    b = backend

    delta = b.array(delta)
    delta = _promote_precision(delta, b)
    b.eval(delta)

    U_available = variance_result.available_basis
    U_available = _promote_precision(U_available, b)
    b.eval(U_available)

    original_shape = b.shape(delta)
    is_2d = len(original_shape) == 2
    available_rank = variance_result.available_rank

    if available_rank == 0:
        logger.warning(
            "VARIANCE NULL SPACE PROJECT: No available directions (utilized=%d/%d). "
            "Returning zero delta.",
            variance_result.utilized_rank,
            variance_result.utilized_rank + variance_result.available_rank
        )
        return b.zeros_like(delta)

    if is_2d:
        # Weight matrix [out_dim, in_dim]
        out_dim = int(original_shape[0])
        in_dim = int(original_shape[1])
        hidden_dim = variance_result.utilized_rank + variance_result.available_rank

        if in_dim != hidden_dim:
            logger.warning(
                "VARIANCE NULL SPACE PROJECT: Dimension mismatch "
                "(delta in_dim=%d, hidden_dim=%d). Returning original.",
                in_dim, hidden_dim
            )
            return delta

        # P_available = U_available @ U_available.T is the projection matrix
        # delta_proj = delta @ P_available = delta @ U_available @ U_available.T
        delta_proj = b.matmul(
            b.matmul(delta, U_available),  # [out_dim, available_rank]
            b.transpose(U_available)  # [available_rank, hidden_dim]
        )  # [out_dim, hidden_dim]
        b.eval(delta_proj)

    else:
        # Vector [in_dim]
        in_dim = int(original_shape[0])
        hidden_dim = variance_result.utilized_rank + variance_result.available_rank

        if in_dim != hidden_dim:
            logger.warning(
                "VARIANCE NULL SPACE PROJECT: Dimension mismatch "
                "(delta dim=%d, hidden_dim=%d). Returning original.",
                in_dim, hidden_dim
            )
            return delta

        # P_available @ delta = U_available @ U_available.T @ delta
        delta_proj = b.matmul(U_available, b.matmul(b.transpose(U_available), delta))
        b.eval(delta_proj)

    # Compute norms for logging
    original_norm = b.sqrt(b.sum(delta * delta))
    projected_norm = b.sqrt(b.sum(delta_proj * delta_proj))
    b.eval(original_norm, projected_norm)

    orig_val = float(b.to_scalar(original_norm))
    proj_val = float(b.to_scalar(projected_norm))

    if orig_val > 0:
        preserved = proj_val / orig_val
    else:
        preserved = 0.0

    logger.debug(
        "VARIANCE NULL SPACE PROJECT: ||delta||=%.4f, ||projected||=%.4f, "
        "preserved=%.2f%% (available_rank=%d)",
        orig_val, proj_val, preserved * 100, available_rank
    )

    return delta_proj


__all__ = [
    "OrthogonalProbeGenerator",
    "OrthogonalProbeResult",
    "SequenceProbeResult",
    "RankAugmentationResult",
    "compute_numerical_rank",
    "compute_null_space_basis",
    "validate_full_rank_coverage",
    "score_tokens_for_null_space",
    "find_null_space_tokens_closed_form",
    "augment_rank_closed_form",
    # Sequence-based probe generation (closed-form token selection)
    "find_null_space_sequences",
    "find_null_space_texts",
    # Trajectory-based null-space discovery
    "TrajectoryResult",
    "TrajectorySubspaceResult",
    "collect_trajectory",
    "compute_trajectory_subspace",
    "compute_trajectory_null_space",
    "collect_trajectories_batch",
    "find_trajectory_null_space",
    # Trajectory-tangent null-space projection
    "TrajectoryTangentResult",
    "compute_trajectory_tangent_null_space",
    "project_delta_to_trajectory_tangent",
    # Variance-based null-space (for full-trajectory cases)
    "VarianceNullSpaceResult",
    "compute_variance_null_space",
    "project_delta_to_variance_null_space",
]
