# Copyright (C) 2025 EthyrosAI LLC / Jason Kempf
#
# This file is part of ModelCypher.
#
# ModelCypher is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ModelCypher is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with ModelCypher.  If not, see <https://www.gnu.org/licenses/>.

"""Entropy dynamics for inference monitoring.

Provides raw geometric measurements from logit entropy during generation.
"""

from __future__ import annotations

import logging
import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from typing import TYPE_CHECKING, Any

from modelcypher.core.domain._backend import get_default_backend
from modelcypher.core.domain.geometry.numerical_stability import (
    division_epsilon,
    machine_epsilon,
)

if TYPE_CHECKING:
    from modelcypher.ports.backend import Array, Backend

logger = logging.getLogger("modelcypher.inference.entropy_dynamics")


@dataclass(frozen=True)
class EntropySample:
    """Raw entropy sample from a generation window."""

    window_id: uuid.UUID
    token_start: int
    token_end: int
    logit_entropy: float
    top_k_variance: float
    latency_ms: float
    source: str | None = None
    correlation_id: uuid.UUID | None = None


@dataclass(frozen=True)
class ConflictAnalysis:
    """Raw conflict metrics between adapter and base model.

    Attributes
    ----------
    mean_kl : float
        Mean KL divergence from adapter to base.
    base_frontier_rate : float
        Fraction of tokens inside the base logit frontier.
    conflict_score : float
        Combined conflict signal: mean_kl * (1 - frontier_rate).
    token_count : int
        Number of tokens measured.
    """

    mean_kl: float
    base_frontier_rate: float
    conflict_score: float
    token_count: int

    @staticmethod
    def compute(
        kl_divergences: list[float | None], base_frontier_hit: list[bool | None]
    ) -> "ConflictAnalysis" | None:
        kl_sum = 0.0
        token_count = 0
        frontier_count = 0

        for kl, hit in zip(kl_divergences, base_frontier_hit):
            if kl is not None and hit is not None:
                token_count += 1
                kl_sum += kl
                if hit:
                    frontier_count += 1

        if token_count == 0:
            return None

        mean_kl = kl_sum / token_count
        frontier_rate = float(frontier_count) / token_count
        conflict_score = mean_kl * (1.0 - frontier_rate)

        return ConflictAnalysis(
            mean_kl=mean_kl,
            base_frontier_rate=frontier_rate,
            conflict_score=conflict_score,
            token_count=token_count,
        )


@dataclass
class EntropyDeltaSample:
    """Raw entropy delta measurements between base and adapter.

    Attributes
    ----------
    token_index : int
        Position of this token in the sequence.
    generated_token : int
        Token ID generated by the adapter.
    base_entropy : float
        Shannon entropy of base model logits.
    base_top_k_variance : float
        Variance of top-k base logits.
    base_top_token : int
        Token ID with highest base probability.
    adapter_entropy : float
        Shannon entropy of adapter logits.
    adapter_top_k_variance : float
        Variance of top-k adapter logits.
    adapter_top_token : int
        Token ID with highest adapter probability.
    latency_ms : float
        Measurement latency in milliseconds.
    """

    token_index: int
    generated_token: int

    # Base metrics
    base_entropy: float
    base_top_k_variance: float
    base_top_token: int

    # Adapter metrics
    adapter_entropy: float
    adapter_top_k_variance: float
    adapter_top_token: int

    latency_ms: float

    id: uuid.UUID = field(default_factory=uuid.uuid4)
    timestamp: datetime = field(default_factory=datetime.utcnow)
    correlation_id: uuid.UUID | None = None
    source: str | None = None

    # Approval metrics
    base_logit_margin: float | None = None
    base_token_logit: float | None = None
    base_rank_fraction: float | None = None
    base_frontier_hit: bool | None = None
    kl_divergence_adapter_to_base: float | None = None

    @property
    def delta(self) -> float:
        """Entropy delta: base - adapter."""
        return self.base_entropy - self.adapter_entropy

    @property
    def top_token_disagreement(self) -> bool:
        """Whether base and adapter disagree on top token."""
        return self.base_top_token != self.adapter_top_token

    @property
    def variance_delta(self) -> float:
        """Variance delta: base - adapter."""
        return self.base_top_k_variance - self.adapter_top_k_variance

    @property
    def anomaly_score(self) -> float:
        """Entropy ratio measuring base uncertainty relative to adapter confidence."""
        backend = get_default_backend()
        eps = division_epsilon(backend, backend.array([0.0]))
        positive_delta = max(0.0, self.delta)
        return positive_delta / max(self.base_entropy, eps)

    def to_signal_payload(self) -> dict[str, Any]:
        """Convert to signal payload with raw measurements."""
        payload = {
            "id": str(self.id),
            "tokenIndex": self.token_index,
            "generatedToken": self.generated_token,
            "baseEntropy": self.base_entropy,
            "baseVariance": self.base_top_k_variance,
            "adapterEntropy": self.adapter_entropy,
            "adapterVariance": self.adapter_top_k_variance,
            "delta": self.delta,
            "topTokenDisagreement": self.top_token_disagreement,
            "anomalyScore": self.anomaly_score,
            "timestamp": self.timestamp.isoformat(),
            "latencyMs": self.latency_ms,
        }
        if self.base_logit_margin is not None:
            payload["baseLogitMargin"] = self.base_logit_margin
        if self.base_token_logit is not None:
            payload["baseTokenLogit"] = self.base_token_logit
        if self.base_rank_fraction is not None:
            payload["baseRankFraction"] = self.base_rank_fraction
        if self.base_frontier_hit is not None:
            payload["baseFrontierHit"] = self.base_frontier_hit
        if self.kl_divergence_adapter_to_base is not None:
            payload["klDivergenceAdapterToBase"] = self.kl_divergence_adapter_to_base
        if self.correlation_id:
            payload["correlationID"] = str(self.correlation_id)
        if self.source:
            payload["source"] = self.source
        return payload


@dataclass
class EntropyDeltaSessionResult:
    """Aggregated entropy delta metrics over a session.

    Attributes
    ----------
    session_start : datetime
        Session start timestamp.
    session_end : datetime
        Session end timestamp.
    total_tokens : int
        Total tokens generated in session.
    anomaly_count : int
        Number of tokens with positive entropy delta.
    max_anomaly_score : float
        Maximum anomaly score observed.
    avg_delta : float
        Average entropy delta across tokens.
    disagreement_rate : float
        Fraction of tokens where base and adapter disagreed on top token.
    samples : list of EntropyDeltaSample
        Individual token samples.
    """

    session_start: datetime
    session_end: datetime
    total_tokens: int
    anomaly_count: int
    max_anomaly_score: float
    avg_delta: float
    disagreement_rate: float
    samples: list[EntropyDeltaSample]

    session_id: uuid.UUID = field(default_factory=uuid.uuid4)
    correlation_id: uuid.UUID | None = None
    avg_base_logit_margin: float | None = None
    max_base_logit_margin: float | None = None
    conflict_analysis: ConflictAnalysis | None = None

    @property
    def duration_seconds(self) -> float:
        """Session duration in seconds."""
        return (self.session_end - self.session_start).total_seconds()


class LogitEntropyCalculator:
    """Entropy calculation from model logits (1:1 port)."""

    def __init__(
        self,
        backend: "Backend | None" = None,
    ) -> None:
        self._backend = backend or get_default_backend()
        self._epsilon = machine_epsilon(self._backend, self._backend.array([0.0]))

    def compute(self, logits: "Array", skip_variance: bool = False) -> tuple[float, float]:
        b = self._backend
        # Logits: [..., vocab]
        # Flatten to [vocab]
        flat_logits = logits
        if logits.ndim > 1:
            if logits.ndim == 3:  # [batch, seq, vocab]
                flat_logits = logits[0, -1]
            elif logits.ndim == 2:  # [batch, vocab]
                flat_logits = logits[0]

        flat_logits = b.astype(flat_logits, "float32")
        b.eval(flat_logits)  # stable eval

        # Softmax
        max_val = b.max(flat_logits, axis=-1, keepdims=True)
        shifted = flat_logits - max_val
        exp_shifted = b.exp(shifted)
        sum_exp = b.sum(exp_shifted, axis=-1, keepdims=True)
        probs = exp_shifted / sum_exp

        # Entropy
        log_probs = b.log(probs + self._epsilon)
        entropy = -b.sum(probs * log_probs, axis=-1)

        # Variance
        variance_val = 0.0
        if not skip_variance:
            mean_val = b.mean(flat_logits, axis=-1, keepdims=True)
            squared_diff = (flat_logits - mean_val) ** 2
            variance = b.mean(squared_diff, axis=-1)
            b.eval(entropy, variance)
            return (float(b.to_scalar(entropy)), float(b.to_scalar(variance)))

        b.eval(entropy)
        return (float(b.to_scalar(entropy)), variance_val)


class LogitDivergenceCalculator:
    """KL divergence calculator."""

    def __init__(
        self,
        backend: "Backend | None" = None,
    ) -> None:
        self._backend = backend or get_default_backend()
        self._epsilon = machine_epsilon(self._backend, self._backend.array([0.0]))

    def stable_softmax(self, flat_logits: "Array") -> "Array":
        b = self._backend
        max_val = b.max(flat_logits, axis=-1, keepdims=True)
        shifted = flat_logits - max_val
        exp_shifted = b.exp(shifted)
        sum_exp = b.sum(exp_shifted, axis=-1, keepdims=True)
        return exp_shifted / sum_exp

    def kl_divergence(self, primary_logits: "Array", probe_logits: "Array") -> float:
        b = self._backend
        # Flatten
        p_flat = primary_logits
        q_flat = probe_logits
        if primary_logits.ndim > 1:
            p_flat = primary_logits[0, -1] if primary_logits.ndim == 3 else primary_logits[0]
        if probe_logits.ndim > 1:
            q_flat = probe_logits[0, -1] if probe_logits.ndim == 3 else probe_logits[0]

        p = self.stable_softmax(p_flat)
        q = self.stable_softmax(q_flat)

        log_p = b.log(p + self._epsilon)
        log_q = b.log(q + self._epsilon)

        kl = b.sum(p * (log_p - log_q), axis=-1)
        b.eval(kl)
        return max(0.0, float(b.to_scalar(kl)))


class EntropyDeltaTracker:
    """Tracks entropy differences between two model passes."""

    def __init__(
        self,
        *,
        source: str | None = None,
        backend: "Backend | None" = None,
        router: Any | None = None,
    ) -> None:
        self.source = source
        self._backend = backend or get_default_backend()
        self.calculator = LogitEntropyCalculator(backend=self._backend)
        self._router = router
        self.samples: list[EntropyDeltaSample] = []
        self.session_active = False
        self.correlation_id: uuid.UUID | None = None
        self.session_start: datetime | None = None

    def start_session(self, correlation_id: uuid.UUID | None = None):
        self.session_active = True
        self.correlation_id = correlation_id or uuid.uuid4()
        self.session_start = datetime.utcnow()
        self.samples = []

    def record_dual_entropy(
        self,
        base_logits: "Array",
        adapter_logits: "Array",
        token_index: int,
        generated_token: int,
    ) -> EntropyDeltaSample:
        start_time = time.perf_counter()
        b = self._backend

        base_ent, base_var = self.calculator.compute(base_logits, skip_variance=False)
        adap_ent, adap_var = self.calculator.compute(adapter_logits, skip_variance=False)

        # Top token extraction
        def get_top(logits: "Array") -> int:
            flat = logits
            if logits.ndim > 1:
                flat = logits[0, -1] if logits.ndim == 3 else logits[0]
            idx = b.argmax(flat, axis=-1)
            b.eval(idx)
            return int(b.to_scalar(idx))

        base_top = get_top(base_logits)
        adap_top = get_top(adapter_logits)

        latency_ms = (time.perf_counter() - start_time) * 1000

        sample = EntropyDeltaSample(
            token_index=token_index,
            generated_token=generated_token,
            base_entropy=base_ent,
            base_top_k_variance=base_var,
            base_top_token=base_top,
            adapter_entropy=adap_ent,
            adapter_top_k_variance=adap_var,
            adapter_top_token=adap_top,
            latency_ms=latency_ms,
            correlation_id=self.correlation_id,
            source=self.source,
        )

        self.samples.append(sample)
        return sample

    def record_step(self, sample: EntropyDeltaSample) -> EntropyDeltaSample:
        """Record a precomputed entropy delta sample."""
        self.samples.append(sample)
        return sample

    def end_session(self) -> EntropyDeltaSessionResult:
        end_time = datetime.utcnow()
        self.session_active = False

        anomaly_count = sum(1 for s in self.samples if s.delta > 0.0)
        max_score = max((s.anomaly_score for s in self.samples), default=0.0)
        avg_delta = sum((s.delta for s in self.samples), start=0.0) / max(1, len(self.samples))
        disagreement = sum(1 for s in self.samples if s.top_token_disagreement)
        disagreement_rate = disagreement / max(1, len(self.samples))

        # Conflict Analysis
        kls = [s.kl_divergence_adapter_to_base for s in self.samples]
        approvals = [s.base_frontier_hit for s in self.samples]
        conflict = ConflictAnalysis.compute(kls, approvals)

        return EntropyDeltaSessionResult(
            session_start=self.session_start or end_time,
            session_end=end_time,
            total_tokens=len(self.samples),
            anomaly_count=anomaly_count,
            max_anomaly_score=max_score,
            avg_delta=avg_delta,
            disagreement_rate=disagreement_rate,
            samples=self.samples,
            correlation_id=self.correlation_id,
            conflict_analysis=conflict,
        )
