#!/usr/bin/env python3
"""Experiment 13: Ranking Loss vs MSE Loss.

Tests whether optimizing for ranking preservation instead of MSE improves
token accuracy after compression.

Hypothesis: Starting from RMT-compressed T and optimizing for ranking
should improve token accuracy on layers that fail with MSE alone.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

import logging

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)


def run_experiment():
    """Compare MSE vs ranking-preserving optimization."""
    import mlx.core as mx

    from modelcypher.backends import initialize_default_backend
    from modelcypher.core.domain._backend import get_default_backend
    from modelcypher.core.domain.compression import (
        RMTAwareCompressor,
        RankingPreservingOptimizer,
    )

    initialize_default_backend()
    backend = get_default_backend()
    logger.info(f"Using backend: {type(backend).__name__}")

    # Load model
    model_path = "/Volumes/CodeCypher/models/mlx-community/DeepSeek-R1-0528-Qwen3-8B-bf16"
    logger.info(f"Loading model: {model_path}")

    from mlx_lm import load
    model, tokenizer = load(model_path)

    # Use more calibration prompts for better optimization
    calibration_prompts = [
        "The capital of France is",
        "In mathematics, the derivative of",
        "The largest planet in our solar system is",
        "Water freezes at",
        "The speed of light is approximately",
        "Photosynthesis is the process by which",
        "The human heart has",
        "DNA stands for",
        "The chemical symbol for gold is",
        "Shakespeare wrote",
        "The Great Wall of China was built",
        "E = mc² was discovered by",
        "The mitochondria is",
        "Python is a programming language that",
        "Machine learning algorithms",
        "The stock market",
        "Climate change refers to",
        "Quantum mechanics describes",
        "The Renaissance was a period",
        "Artificial intelligence",
        "The theory of evolution states",
        "Neurons in the brain",
        "The periodic table organizes",
        "Gravity is a force that",
        "The internet was invented",
        "Vaccines work by",
        "The moon orbits",
        "Sound travels through",
        "Electricity is generated by",
        "Plants need sunlight to",
    ]

    held_out_prompts = [
        "The theory of relativity states",
        "Neurons transmit signals by",
        "Chemical bonds form when",
        "Democracy originated in",
    ]

    cal_tokens = [tokenizer.encode(p) for p in calibration_prompts]
    held_tokens = [tokenizer.encode(p) for p in held_out_prompts]

    # Initialize modules
    compressor = RMTAwareCompressor(backend=backend)
    optimizer = RankingPreservingOptimizer(backend=backend)

    # Test layers that showed mixed results in exp12
    # Layer 5 and 6 failed, layer 1,2,7 succeeded
    test_layers = [1, 5, 6, 7]

    results = []

    for layer_idx in test_layers:
        logger.info(f"\n{'='*60}")
        logger.info(f"Layer {layer_idx}")
        logger.info(f"{'='*60}")

        # Collect calibration activations
        cal_inputs = []
        cal_outputs = []

        for tokens in cal_tokens:
            input_ids = mx.array([tokens])
            mlp_input = None
            mlp_output = None

            layer = model.model.layers[layer_idx]
            original_mlp = layer.mlp

            class MLPHook:
                def __init__(self, mlp):
                    self.mlp = mlp
                def __call__(self, x):
                    nonlocal mlp_input, mlp_output
                    mlp_input = x
                    mlp_output = self.mlp(x)
                    return mlp_output

            layer.mlp = MLPHook(original_mlp)
            try:
                _ = model(input_ids)
                mx.eval(mlp_input, mlp_output)
                cal_inputs.append(mlp_input[0, -1, :])
                cal_outputs.append(mlp_output[0, -1, :])
            finally:
                layer.mlp = original_mlp

        X_cal = mx.stack(cal_inputs).astype(mx.float32)
        Y_cal = mx.stack(cal_outputs).astype(mx.float32)
        mx.eval(X_cal, Y_cal)

        # Convert to backend arrays
        X_backend = backend.array(X_cal)
        Y_backend = backend.array(Y_cal)

        # Step 1: RMT compression
        logger.info("\n--- RMT Compression ---")
        rmt_result = compressor.compress_layer(X_backend, Y_backend)
        logger.info(f"RMT signal_rank: {rmt_result.signal_rank}/{rmt_result.total_rank}")
        logger.info(f"RMT recon error: {rmt_result.reconstruction_error:.4f}")

        # Step 2: Ranking optimization starting from RMT result
        logger.info("\n--- Ranking Optimization ---")
        ranking_result = optimizer.optimize(
            X_backend, Y_backend, rmt_result.T,
            max_iterations=10,  # Reduced for testing
            top_k=3,
        )
        logger.info(f"Ranking iterations: {ranking_result.iterations}")
        logger.info(f"Initial top1: {ranking_result.initial_top1:.1%}")
        logger.info(f"Final top1: {ranking_result.top1_preserved:.1%}")
        logger.info(f"Rankings preserved: {ranking_result.rankings_preserved:.1%}")

        # Step 3: Evaluate on held-out with actual model inference
        logger.info("\n--- Held-Out Evaluation ---")

        def evaluate_with_model(T):
            """Evaluate compression with actual model inference."""
            correct = 0
            total = 0

            T_mx = mx.array(backend.tolist(T)).astype(mx.float32)
            mx.eval(T_mx)

            for tokens in held_tokens:
                input_ids = mx.array([tokens])

                # Original logits
                orig_logits = model(input_ids)
                mx.eval(orig_logits)
                orig_top = int(mx.argmax(orig_logits[0, -1, :]).item())

                # Compressed
                layer = model.model.layers[layer_idx]
                original_mlp = layer.mlp

                class CompressedMLP:
                    def __init__(self, T):
                        self.T = T
                    def __call__(self, x):
                        return mx.matmul(x, self.T.T)

                layer.mlp = CompressedMLP(T_mx)
                try:
                    comp_logits = model(input_ids)
                    mx.eval(comp_logits)
                    comp_top = int(mx.argmax(comp_logits[0, -1, :]).item())

                    if comp_top == orig_top:
                        correct += 1
                    total += 1
                finally:
                    layer.mlp = original_mlp

            return correct / total if total > 0 else 0.0

        rmt_accuracy = evaluate_with_model(rmt_result.T)
        ranking_accuracy = evaluate_with_model(ranking_result.T)

        logger.info(f"RMT token accuracy: {rmt_accuracy:.1%}")
        logger.info(f"Ranking-optimized accuracy: {ranking_accuracy:.1%}")

        improvement = ranking_accuracy - rmt_accuracy
        if improvement > 0:
            logger.info(f">>> IMPROVEMENT: +{improvement:.1%}")
        elif improvement < 0:
            logger.info(f">>> DEGRADATION: {improvement:.1%}")
        else:
            logger.info(f">>> NO CHANGE")

        results.append({
            "layer": layer_idx,
            "rmt_accuracy": rmt_accuracy,
            "ranking_accuracy": ranking_accuracy,
            "improvement": improvement,
            "initial_top1": ranking_result.initial_top1,
            "final_top1": ranking_result.top1_preserved,
            "iterations": ranking_result.iterations,
        })

    # Summary
    logger.info(f"\n{'='*60}")
    logger.info("SUMMARY")
    logger.info(f"{'='*60}")

    logger.info(f"\n{'Layer':<8} {'RMT Acc':<12} {'Ranking Acc':<12} {'Improvement':<12}")
    logger.info("-" * 50)

    for r in results:
        logger.info(
            f"{r['layer']:<8} {r['rmt_accuracy']*100:<12.1f} "
            f"{r['ranking_accuracy']*100:<12.1f} {r['improvement']*100:+.1f}"
        )

    # Check hypothesis
    improvements = [r['improvement'] for r in results]
    avg_improvement = sum(improvements) / len(improvements) if improvements else 0

    logger.info(f"\n--- Hypothesis Check ---")
    logger.info(f"Average improvement: {avg_improvement*100:+.1f}%")

    if avg_improvement > 0.05:
        logger.info(">>> HYPOTHESIS SUPPORTED: Ranking optimization helps")
    elif avg_improvement < -0.05:
        logger.info(">>> HYPOTHESIS REJECTED: Ranking optimization hurts")
    else:
        logger.info(">>> INCONCLUSIVE: No significant difference")


if __name__ == "__main__":
    run_experiment()
