#!/usr/bin/env python3
"""Experiment 19: Maximum Lossless Compression.

Tests combining safe zones to achieve maximum lossless compression.

From Exp 15 and 18:
- Safe individual layers: [8, 20, 23, 25, 26, 27, 33]
- Safe contiguous pairs: [7,8], [22,23], [23,24], [24,25]
- Encoding zone (0-6): Never compress

Hypothesis: We can combine [7,8] + [22-27] for >15% compression at 100% accuracy.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

import logging

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)


def run_experiment():
    """Test maximum safe layer combinations."""
    import mlx.core as mx

    from modelcypher.backends import initialize_default_backend
    from modelcypher.core.domain._backend import get_default_backend
    from modelcypher.core.domain.compression import RMTAwareCompressor

    initialize_default_backend()
    backend = get_default_backend()
    logger.info(f"Using backend: {type(backend).__name__}")

    # Load model
    model_path = "/Volumes/CodeCypher/models/mlx-community/DeepSeek-R1-0528-Qwen3-8B-bf16"
    logger.info(f"Loading model: {model_path}")

    from mlx_lm import load
    model, tokenizer = load(model_path)

    n_layers = len(model.model.layers)
    logger.info(f"Model has {n_layers} layers")

    # More calibration prompts for better coverage
    calibration_prompts = [
        "The capital of France is",
        "In mathematics, the derivative of",
        "The largest planet in our solar system is",
        "Water freezes at",
        "The speed of light is approximately",
        "Photosynthesis is the process by which",
        "The human heart has",
        "DNA stands for",
        "The chemical symbol for gold is",
        "Shakespeare wrote",
        "The Great Wall of China was built",
        "E = mc² was discovered by",
        "The mitochondria is",
        "Python is a programming language that",
        "Machine learning algorithms",
        "The stock market",
        "Climate change refers to",
        "Quantum mechanics describes",
        "The Renaissance was a period",
        "Artificial intelligence",
        "The theory of evolution states",
        "Neurons in the brain",
        "The periodic table organizes",
        "Gravity is a force that",
        "The internet was invented",
        "Vaccines work by",
        "The moon orbits",
        "Sound travels through",
        "Electricity is generated by",
        "Plants need sunlight to",
        "The Amazon rainforest",
        "Black holes are",
    ]

    held_out_prompts = [
        "The theory of relativity states",
        "Neurons transmit signals by",
        "Chemical bonds form when",
        "Democracy originated in",
        "The Eiffel Tower was built",
        "Oxygen is essential for",
        "The human genome contains",
        "Tectonic plates move",
    ]

    cal_tokens = [tokenizer.encode(p) for p in calibration_prompts]
    held_tokens = [tokenizer.encode(p) for p in held_out_prompts]

    compressor = RMTAwareCompressor(backend=backend)

    # Candidate safe zones
    safe_zones = {
        "zone_7_8": [7, 8],
        "zone_22_27": [22, 23, 24, 25, 26, 27],
        "zone_20_27": [20, 21, 22, 23, 24, 25, 26, 27],
        "all_100pct": [8, 20, 23, 25, 26, 27, 33],
        "combined_7_8_22_27": [7, 8, 22, 23, 24, 25, 26, 27],
    }

    # Pre-compress needed layers
    needed_layers = set()
    for layers in safe_zones.values():
        needed_layers.update(layers)

    logger.info(f"\n--- Pre-compressing layers {sorted(needed_layers)} ---")

    layer_T = {}

    for layer_idx in sorted(needed_layers):
        logger.info(f"Compressing layer {layer_idx}...")

        cal_inputs = []
        cal_outputs = []

        for tokens in cal_tokens:
            input_ids = mx.array([tokens])
            mlp_input = None
            mlp_output = None

            layer = model.model.layers[layer_idx]
            original_mlp = layer.mlp

            class MLPHook:
                def __init__(self, mlp):
                    self.mlp = mlp
                def __call__(self, x):
                    nonlocal mlp_input, mlp_output
                    mlp_input = x
                    mlp_output = self.mlp(x)
                    return mlp_output

            layer.mlp = MLPHook(original_mlp)
            try:
                _ = model(input_ids)
                mx.eval(mlp_input, mlp_output)
                cal_inputs.append(mlp_input[0, -1, :])
                cal_outputs.append(mlp_output[0, -1, :])
            finally:
                layer.mlp = original_mlp

        X_cal = mx.stack(cal_inputs).astype(mx.float32)
        Y_cal = mx.stack(cal_outputs).astype(mx.float32)
        mx.eval(X_cal, Y_cal)

        X_backend = backend.array(X_cal)
        Y_backend = backend.array(Y_cal)

        rmt_result = compressor.compress_layer(X_backend, Y_backend)
        T_mx = mx.array(backend.tolist(rmt_result.T)).astype(mx.float32)
        mx.eval(T_mx)
        layer_T[layer_idx] = T_mx

    def evaluate_layer_set(layer_indices):
        """Evaluate accuracy with a set of compressed layers."""
        correct = 0
        total = 0

        for tokens in held_tokens:
            input_ids = mx.array([tokens])

            # Get original prediction
            orig_logits = model(input_ids)
            mx.eval(orig_logits)
            orig_top = int(mx.argmax(orig_logits[0, -1, :]).item())

            # Apply compression to specified layers
            original_mlps = {}
            for idx in layer_indices:
                layer = model.model.layers[idx]
                original_mlps[idx] = layer.mlp

                class CompressedMLP:
                    def __init__(self, T):
                        self.T = T
                    def __call__(self, x):
                        return mx.matmul(x, self.T.T)

                layer.mlp = CompressedMLP(layer_T[idx])

            try:
                comp_logits = model(input_ids)
                mx.eval(comp_logits)
                comp_top = int(mx.argmax(comp_logits[0, -1, :]).item())

                if comp_top == orig_top:
                    correct += 1
                total += 1
            finally:
                for idx in layer_indices:
                    model.model.layers[idx].mlp = original_mlps[idx]

        return correct / total if total > 0 else 0.0

    # Test each zone
    logger.info(f"\n{'='*60}")
    logger.info("TESTING SAFE ZONES")
    logger.info(f"{'='*60}")

    results = []

    for name, layers in safe_zones.items():
        accuracy = evaluate_layer_set(layers)
        compression = len(layers) / n_layers * 100
        results.append({
            "name": name,
            "layers": layers,
            "n_layers": len(layers),
            "accuracy": accuracy,
            "compression": compression,
        })
        logger.info(f"\n{name}:")
        logger.info(f"  Layers: {layers}")
        logger.info(f"  Accuracy: {accuracy:.1%}")
        logger.info(f"  Compression: {compression:.1f}% of model")

    # Summary
    logger.info(f"\n{'='*60}")
    logger.info("SUMMARY")
    logger.info(f"{'='*60}")

    logger.info(f"\n{'Zone':<25} {'Layers':<8} {'Accuracy':<12} {'Compression':<12}")
    logger.info("-" * 60)

    for r in results:
        logger.info(
            f"{r['name']:<25} {r['n_layers']:<8} {r['accuracy']*100:<12.1f} {r['compression']:<12.1f}"
        )

    # Find best at 100%
    perfect = [r for r in results if r["accuracy"] >= 1.0 - 1e-6]
    if perfect:
        best = max(perfect, key=lambda r: r["compression"])
        logger.info(f"\n>>> BEST 100% COMPRESSION: {best['name']} = {best['compression']:.1f}%")
    else:
        logger.info(f"\n>>> NO 100% ACCURACY COMBINATIONS FOUND")
        # Find best overall
        best = max(results, key=lambda r: r["accuracy"])
        logger.info(f">>> BEST ACCURACY: {best['name']} = {best['accuracy']:.1%} ({best['compression']:.1f}%)")

    # Try greedy expansion from best safe zone
    logger.info(f"\n{'='*60}")
    logger.info("GREEDY EXPANSION")
    logger.info(f"{'='*60}")

    # Start from zone_22_27 (known good)
    current_layers = [22, 23, 24, 25, 26, 27]
    candidates = [7, 8, 20, 21, 28, 29, 30, 31, 32, 33]

    # Ensure we have T matrices for candidates
    for layer_idx in candidates:
        if layer_idx not in layer_T:
            logger.info(f"Compressing layer {layer_idx} for greedy expansion...")

            cal_inputs = []
            cal_outputs = []

            for tokens in cal_tokens:
                input_ids = mx.array([tokens])
                mlp_input = None
                mlp_output = None

                layer = model.model.layers[layer_idx]
                original_mlp = layer.mlp

                class MLPHook:
                    def __init__(self, mlp):
                        self.mlp = mlp
                    def __call__(self, x):
                        nonlocal mlp_input, mlp_output
                        mlp_input = x
                        mlp_output = self.mlp(x)
                        return mlp_output

                layer.mlp = MLPHook(original_mlp)
                try:
                    _ = model(input_ids)
                    mx.eval(mlp_input, mlp_output)
                    cal_inputs.append(mlp_input[0, -1, :])
                    cal_outputs.append(mlp_output[0, -1, :])
                finally:
                    layer.mlp = original_mlp

            X_cal = mx.stack(cal_inputs).astype(mx.float32)
            Y_cal = mx.stack(cal_outputs).astype(mx.float32)
            mx.eval(X_cal, Y_cal)

            X_backend = backend.array(X_cal)
            Y_backend = backend.array(Y_cal)

            rmt_result = compressor.compress_layer(X_backend, Y_backend)
            T_mx = mx.array(backend.tolist(rmt_result.T)).astype(mx.float32)
            mx.eval(T_mx)
            layer_T[layer_idx] = T_mx

    # Test current baseline
    base_accuracy = evaluate_layer_set(current_layers)
    logger.info(f"\nBaseline {current_layers}: {base_accuracy:.1%}")

    # Try adding each candidate
    for candidate in candidates:
        test_layers = sorted(current_layers + [candidate])
        accuracy = evaluate_layer_set(test_layers)
        logger.info(f"+ layer {candidate}: {accuracy:.1%} ({len(test_layers)} layers = {len(test_layers)/n_layers*100:.1f}%)")

        if accuracy >= 1.0 - 1e-6:
            current_layers = test_layers
            logger.info(f"  >>> ADDED (still 100%)")

    # Final result
    final_accuracy = evaluate_layer_set(current_layers)
    final_compression = len(current_layers) / n_layers * 100

    logger.info(f"\n{'='*60}")
    logger.info("FINAL RESULT")
    logger.info(f"{'='*60}")
    logger.info(f"Layers: {current_layers}")
    logger.info(f"Count: {len(current_layers)}/{n_layers}")
    logger.info(f"Accuracy: {final_accuracy:.1%}")
    logger.info(f"Compression: {final_compression:.1f}%")

    if final_compression > 15:
        logger.info(f"\n>>> HYPOTHESIS CONFIRMED: >{15}% lossless compression achieved!")
    else:
        logger.info(f"\n>>> HYPOTHESIS NOT YET CONFIRMED: {final_compression:.1f}% < 15%")


if __name__ == "__main__":
    run_experiment()
