from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

Array = Any


@runtime_checkable
class Backend(Protocol):
    def array(self, data: Any, dtype: Any | None = None) -> Array: ...
    def zeros(self, shape: tuple[int, ...], dtype: Any | None = None) -> Array: ...
    def ones(self, shape: tuple[int, ...], dtype: Any | None = None) -> Array: ...
    def reshape(self, array: Array, shape: tuple[int, ...]) -> Array: ...
    def squeeze(self, array: Array, axis: int | None = None) -> Array: ...
    def transpose(self, array: Array) -> Array: ...
    def matmul(self, lhs: Array, rhs: Array) -> Array: ...
    def sum(self, array: Array, axis: int | None = None, keepdims: bool = False) -> Array: ...
    def max(self, array: Array, axis: int | None = None, keepdims: bool = False) -> Array: ...
    def sqrt(self, array: Array) -> Array: ...
    def exp(self, array: Array) -> Array: ...
    def log(self, array: Array) -> Array: ...
    def maximum(self, lhs: Array, rhs: Array) -> Array: ...
    def minimum(self, lhs: Array, rhs: Array) -> Array: ...
    def abs(self, array: Array) -> Array: ...
    def astype(self, array: Array, dtype: Any) -> Array: ...
    def svd(self, array: Array, compute_uv: bool = True) -> tuple[Array, Array, Array] | Array: ...
    def dequantize(
        self,
        weight: Array,
        scales: Array,
        biases: Array | None,
        group_size: int,
        bits: int,
        mode: str,
    ) -> Array: ...
    def eval(self, *arrays: Array) -> None: ...
    def to_numpy(self, array: Array) -> Any: ...
