# Copyright (C) 2025 EthyrosAI LLC / Jason Kempf
#
# This file is part of ModelCypher.
#
# ModelCypher is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ModelCypher is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with ModelCypher.  If not, see <https://www.gnu.org/licenses/>.

from __future__ import annotations

from typing import Protocol

from modelcypher.core.domain.geometry.manifold_profile import ManifoldPoint, ManifoldProfile
from modelcypher.core.domain.models import (
    CheckpointRecord,
    CompareSession,
    DatasetInfo,
    EvaluationResult,
    ModelInfo,
    TrainingJob,
)
from modelcypher.core.domain.training import TrainingStatus


class ModelStore(Protocol):
    def list_models(self) -> list[ModelInfo]: ...
    def get_model(self, model_id: str) -> ModelInfo | None: ...
    def register_model(self, model: ModelInfo) -> None: ...
    def delete_model(self, model_id: str) -> None: ...


class DatasetStore(Protocol):
    def list_datasets(self) -> list[DatasetInfo]: ...
    def get_dataset(self, dataset_id: str) -> DatasetInfo | None: ...
    def register_dataset(self, dataset: DatasetInfo) -> None: ...
    def delete_dataset(self, dataset_id: str) -> None: ...


class JobStore(Protocol):
    def save_job(self, job: TrainingJob) -> None: ...
    def update_job(self, job: TrainingJob) -> None: ...
    def list_jobs(self, status: TrainingStatus | None = None, active_only: bool = False) -> list[TrainingJob]: ...
    def get_job(self, job_id: str) -> TrainingJob | None: ...
    def delete_job(self, job_id: str) -> None: ...
    def list_checkpoints(self, job_id: str | None = None) -> list[CheckpointRecord]: ...
    def add_checkpoint(self, checkpoint: CheckpointRecord) -> None: ...
    def delete_checkpoint(self, path: str) -> None: ...


class EvaluationStore(Protocol):
    def list_evaluations(self, limit: int) -> list[EvaluationResult]: ...
    def save_evaluation(self, result: EvaluationResult) -> None: ...
    def get_evaluation(self, eval_id: str) -> EvaluationResult | None: ...


class CompareStore(Protocol):
    def list_sessions(self, limit: int, status: str | None = None) -> list[CompareSession]: ...
    def save_session(self, session: CompareSession) -> None: ...
    def get_session(self, session_id: str) -> CompareSession | None: ...


class ManifoldProfileStore(Protocol):
    def load(self, model_id: str) -> ManifoldProfile | None: ...
    def list(self, limit: int | None = None) -> list[ManifoldProfile]: ...
    def save(self, profile: ManifoldProfile) -> None: ...
    def delete(self, model_id: str) -> None: ...
    def add_point(self, point: ManifoldPoint, model_id: str, model_name: str) -> None: ...
    def get_statistics(self, model_id: str) -> ManifoldProfile.Statistics | None: ...
