from __future__ import annotations

from typing import Protocol

from modelcypher.core.domain.models import TrainingJob
from modelcypher.core.domain.training import PreflightResult, TrainingConfig


class TrainingEngine(Protocol):
    def preflight(self, config: TrainingConfig) -> PreflightResult: ...
    def start(self, config: TrainingConfig, stream_events: bool = False) -> tuple[TrainingJob, list[dict]]: ...
    def status(self, job_id: str) -> TrainingJob: ...
    def pause(self, job_id: str) -> TrainingJob: ...
    def resume(self, job_id: str) -> TrainingJob: ...
    def cancel(self, job_id: str) -> TrainingJob: ...
    def logs(self, job_id: str, tail: int = 100) -> list[str]: ...
